### ISSUE TITLE
[1.0.4] Incompatibility with slots added by HotbarPlus

### ISSUE THREAD

**Issue by SeedyMcSeedface** [Shaosil/LethalCompanyMods-GeneralImprovements#1]
Despite having more than 4 slots from HotbarPlus, I am not able to pick up more than four items as it says "Inventory is full".
I was having no issues with 1.0.3, and had this issue come up after updating.

Screenshots of the issue. I have the empty slots selected and can switch to them, but I can't pick up anything else.

![1966720_20240105141923_1](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/155770932/597145c6-eecf-4d03-bdb7-888d1bf71040)
![1966720_20240105141936_1](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/155770932/53291a87-5166-4306-80aa-f4767c4b0b93)

The screenshots were taken with only HotbarPlus and GeneralImprovements, along with their respective dependencies, enabled.

**Comment by Shaosil** [comment]
Dangit I know what I broke. I was making it compatible with ReservedItemSlot mods so it wouldn't shift them over when dropping stuff, and limited it to 4 slots to check. I'll get this fixed today with 1.0.5, sorry :)

**Comment by SeedyMcSeedface** [comment]
All good! Wanted to make sure this was known quickly so it could be fixed as soon as you're able.

**Comment by Shaosil** [comment]
Tested and fixed in v1.0.5, which should show up in Thunderstore shortly. Closing. Thanks for the heads up!
