### ISSUE TITLE
Snap rotation keybinds

### ISSUE THREAD

**Issue by dragonmcmx1** [Shaosil/LethalCompanyMods-GeneralImprovements#10]
Love the mod and the frequent new additions, but I would appreciate the ability to config the Left Shift and Left Alt Keybinds for the new build mode rotation options.

Shift+Alt in Windows changes your keyboard language. Some people like myself use multiple input language settings so this is bit of an inconvenience.

Alt+R on the other hand opens some kind of performance overlay window for NVIDIA users instead of doing what it's supposed to do in the mod.

**Comment by Shaosil** [comment]
Good suggestion, I'll try to have that in the next release

**Comment by Shaosil** [comment]
This is now configurable in v1.0.13. I can't guarantee the game won't behave strangely if you try to use a key it already checks for of course, but in theory it's all custom now :)

**Comment by YoBii** [comment]
Small question on this topic. I didn't find it in the list of supported binds but can we set mouse buttons for these? Possibly have a configurable bind for rotate itself?

With big modpacks there are so many keybinds already. One or multiple emote wheels. Walkie and flashlight hotkey. AdvancedCompany now has added a mobile terminal that reserves a key. All the Vanilla binds for seconday, tertiary item use. Plus the issue with global hotkeys with Windows or 3rd party apps that OP mentioned.

I'm simply running out of keys here. In furniture edit mode left mouse button doesn't do anything so it could be used. I think I'd prefer something like this
- LMB: Rotate (currently vanilla bound to 'R')
- some keybind e.g. 'R': CCW rotate
   - if possible removing scan action from RMB in furniture edit mode and using that for CCW rotate would be 🔥
- some keybind e.g. LShift: when held, removes snapping for the two actions above

Would make this feature much more accessible or rather less of a hassle to set up the keybinds imo

**Comment by Shaosil** [comment]
I'll have to change the way it's handling looking for keypresses a bit because those are all the keys the method I'm using supports, but yeah, that was bugging me too. I'll look into this.

**Comment by Shaosil** [comment]
Update on this one - I updated the modifier keybinds to support most mouse buttons, and if you re-assign the Turn Furniture key from the vanilla keybinds screen, it will work with it. So you can use LMB to rotate by changing it in vanilla, but it now also works with the snap stuff. Closing as complete.
