### ISSUE TITLE
Main monitor shows external camera instead of moon info/map

### ISSUE THREAD

**Issue by MightyBunch** [Shaosil/LethalCompanyMods-GeneralImprovements#100]
So if "UseBetterMonitors = false" main monitor shows external camera instead of moon info/map. Also, button "Turn on/off" is not working. It only appears in v1.1.5.

**Comment by Shaosil** [comment]
Looking into this ASAP, others have reported similar issues

**Comment by Shaosil** [comment]
I added some null checks that fixed a few things, this included I believe. It's in v1.1.6, going live shortly, can you check whether it's fixed on your end when you can and I can close this? Thanks!

**Comment by MightyBunch** [comment]
The monitor now displays the correct information. However, it seems that when you turn it off and on again, only the main monitor turns on, while the others remain off. And I'm not sure if it's intended or not, but the default camera monitors, which display external and internal views, are not turning off at all.

**Comment by Shaosil** [comment]
Ah yeah I see the problem with that - I'll leave this open for now and update here when it's fixed in the next update. Thanks for looking into it.

**Comment by Shaosil** [comment]
Ok this should be fixed in v1.1.7, going live shortly
