### ISSUE TITLE
More suits bugged

### ISSUE THREAD

**Issue by Nin9sKi** [Shaosil/LethalCompanyMods-GeneralImprovements#102]
Beside what others said; More Suits isn't compatible anymore. Suits are filled the ship with the last update, monitors are all bugged, health station isn't there anymore

**Comment by Nin9sKi** [comment]
All monitors dont show anything

**Comment by Shaosil** [comment]
I added some null checks that fixed a few things, this included I believe. It's in v1.1.6, going live shortly, can you check whether it's fixed on your end when you can and I can close this? Thanks!

**Comment by Nin9sKi** [comment]
Did a quick solo run and everything looks good.

Issues that are not there anymore:
Respawn fixed
Monitors Fixed
Compatibility with mother mods (specifically MoreSuits) fixed
Health Station fixed

Thank you♥

**Comment by Shaosil** [comment]
Excellent thanks for checking!
