### ISSUE TITLE
Extra Monitor does not turn back on.

### ISSUE THREAD

**Issue by riverbible** [Shaosil/LethalCompanyMods-GeneralImprovements#103]
https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/155571938/0efd1390-6771-4b64-88d1-7347a15519ac

Ayo

Why won't my ExtraMonitor turn on again?

This is version 1.1.6

**Comment by Shaosil** [comment]
This is a result of a panic fix from breaking a bunch of stuff in 1.1.5 ha, I'll have this resolved in the next version

**Comment by Shaosil** [comment]
Fixed in v1.1.7, going live shortly
