### ISSUE TITLE
light switch display

### ISSUE THREAD

**Issue by ByblackSun** [Shaosil/LethalCompanyMods-GeneralImprovements#104]
This function requires an extremely close distance to show where the switch is.
![20240201163247_1](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/155830927/6c2e84cf-4c62-454b-9e55-06080c3209f9)

I used this before, but after installing this mod, it didn’t work.
https://inscryption.thunderstore.io/c/lethal-company/p/Karster/Light_Switch_Scan_Node/

Sometimes the displayed distance becomes normal again.

**Comment by Shaosil** [comment]
I doubled the distance it can be scanned in v1.1.7 which is going live shortly, I tested and it can be scanned from the other side of the ship now (provided there is nothing blocking the view of it, like everything else)
