### ISSUE TITLE
Can port monitor related content to new MODs

### ISSUE THREAD

**Issue by smilepeak** [Shaosil/LethalCompanyMods-GeneralImprovements#108]
Currently, the addition of too many features to the GeneralImprovements MOD has caused confusion.
You can create a new MOD for the content related to the monitor.
The GeneralImprovements MOD removes display related functions and serves only as a mod for repairing game content.
Adding additional display features is completely different from the content fixed by the GeneralImprovements MOD, isn't it？
The main issue is that there are too many bugs on the display, which have affected game performance and other bugs.
Therefore, it is entirely possible to create a new MOD to port content related to monitors, while the GeneralImprovements MOD is only used to fix game content.

And there is also the function of AddHealthRechargeStation.
This feature is completely a newly added feature that can be transformed into a new MOD instead of stuffing everything into the GeneralImprovements MOD, which can make the GeneralImprovements very confusing.

I hope you can take my suggestion, thank you

**Comment by DeathWrench** [comment]
But now I have everything configured, General Improvements gets split up into a bunch of different mods, I have to then find those mods and reinstall them all, configure everything over again. There really shouldn't be any confusion since the mod has the monitors stuff set to default anyways. Funnily enough if you just search, most of everything you're talking about is tinier mods that were combined into this one mod to make things more convenient, since having 100+ mods on the mod manager bogs it down completely. This mod is better combined into one since now I don't have to download 10 individual mods, they're all right here and I can toggle them on and off.

**Comment by Shaosil** [comment]
Well there are definitely a subset of people that want me to split those minutes out so I'm conflicted, but one of my goals of this mod is to combine everything I'd like to see in the game into one manageable place. I know that's just preference though.

So right now, if you leave everything in the [ExtraMonitors] section on their default settings, my code should make no changes to anything related to monitors.

There is one more spot I need to check that may affect performance, slightly related to monitors, and make sure I disable that if there's no need for it though. I'll just keep this suggestion open until I do that, at least.

**Comment by dannycreations** [comment]
this is my suggestion
why not just created new mod called maybe "GeneralAddons" that contains "adding something" and changing vanilla experience

GeneralImprovements should only contains "fixing something" like qol, bug fix, performance fix, etc
and should not changing vanilla experience

so "one manageable place" is still "one manageable place", if you got issues you go GeneralImprovements, if you got bored you go GeneralAddons

**Comment by smilepeak** [comment]
> this is my suggestion why not just created new mod called maybe "GeneralAddons" that contains "adding something" and changing vanilla experience
> 
> GeneralImprovements should only contains "fixing something" like qol, bug fix, performance fix, etc and should not changing vanilla experience
> 
> so "one manageable place" is still "one manageable place", if you got issues you go GeneralImprovements, if you got bored you go GeneralAddons

I also think this is good, and there won't be a situation where there are more than a dozen different mods scattered. This is only two mods and two configuration files

**Comment by Shaosil** [comment]
Thanks for the suggestion guys, and I do appreciate the opinions (you're not alone) but I decided to keep the monitor code in this repo for now - it's just personal preference and I like maintaining a singular repo instead of multiple in this case.
