### ISSUE TITLE
[Suggestion] Scannable equipment nodes

### ISSUE THREAD

**Issue by throwitaway99** [Shaosil/LethalCompanyMods-GeneralImprovements#11]
This could surely be something that can be disabled, but being able to scan equipment (such as shovels, extension ladders, flashlights, walkie-talkies, etc.) would be quite useful - something akin to the ScannablePlayerItems mod, except without the misspells in the tooltips (no disrespect to the developer of that mod - I just can't find any sort of means to contact them). It could preferably keep the same blue nodes, and perhaps the (configurable?) hiding of said nodes if the equipment is on the ship to avoid too much clutter.

**Comment by Shaosil** [comment]
I like the suggestion! I'll add it to my todo list

**Comment by Shaosil** [comment]
Finally got around to this, it's configurable now in v1.0.25, going live shortly.
