### ISSUE TITLE
[Bug] Text is being shown incorrectly with UseBetterMonitors=true

### ISSUE THREAD

**Issue by ajsglist** [Shaosil/LethalCompanyMods-GeneralImprovements#114]
Included quick screenshot comparison + current config that is showing the issue.  If you have trouble reproducing, let me know and I'll provide more info on mods/etc.  Thanks!

Incorrectly positioned screen text w/ UseBetterMonitors=true
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/139426529/90ee4c99-088a-421e-b660-f6fb3bcb77d1)

Correctly positioned screen text when falling back to UseBetterMonitors=false
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/139426529/532cc8c5-7193-4ae9-bd49-795275d4da7b)

Config (renamed to .txt to allow upload)
[ShaosilGaming.GeneralImprovements - Copy.txt](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/files/14187507/ShaosilGaming.GeneralImprovements.-.Copy.txt)

Edit: Config above currently has UseBetterMonitors=false because I was grabbing the screenshots.  Flipping that back to UseBetterMonitors=true will give you the config that produced the issue.  Apologies

**Comment by Shaosil** [comment]
This is probably because the camera that captures the picture of those text canvases is positioned a bit imperfectly unless the text is centered. I'll mess with the positioning, thanks for the heads up.

**Comment by Shaosil** [comment]
Didn't find the underlying caused, but I slapped a bandaid fix on it if text is left-aligned. v1.1.9 going live soon.
