### ISSUE TITLE
Incompatible with MasterKey MOD

### ISSUE THREAD

**Issue by smilepeak** [Shaosil/LethalCompanyMods-GeneralImprovements#116]
https://thunderstore.io/c/lethal-company/p/boxofbiscuits97/MasterKey/

Version 1.1.8 is not compatible with MasterKey MOD, as the key will disappear after opening the door

**Comment by Shaosil** [comment]
That's because I had to transpile the ItemActivate method for the key and it now calls DestroyItemInSlot instead of DespawnHeldObject, which is what MasterKey is looking for.

Honestly the best way to fix this is either on MasterKey, or I'll just implement that myself in the next update.

**Comment by Shaosil** [comment]
Added a KeysHaveInfiniteUses setting under [Mechanics] so you don't need MasterKey anymore. v1.1.9 going live soon.
