### ISSUE TITLE
[Suggestion] Show player names only while ship is in orbit, hide when landed

### ISSUE THREAD

**Issue by Hardeh** [Shaosil/LethalCompanyMods-GeneralImprovements#117]
In the latest version option to hide player names was added. I suggest to add an option to hide player names only when ship is landed and show them in orbit.

**Comment by Shaosil** [comment]
Good idea! I'll do that.

**Comment by Shaosil** [comment]
Woops this was fixed as of v1.1.10, forgot to close the issue.
