### ISSUE TITLE
[Suggestion] Option to keep just Gear items when using the teleporters

### ISSUE THREAD

**Issue by stdcall0** [Shaosil/LethalCompanyMods-GeneralImprovements#118]
Currently there are options to keep None, Held, or All inventory items when using the teleporters.

Having an extra "Gear" one to keep just gear items (specifically, those purchasable from the store like flashlight and walkie) would be nice.

**Comment by Shaosil** [comment]
I added a "NonScrap" option for both teleporters in v1.1.10, going live shortly
