### ISSUE TITLE
Purchased items don't fall to the ground upon delivery

### ISSUE THREAD

**Issue by dragonmcmx1** [Shaosil/LethalCompanyMods-GeneralImprovements#12]
They just kinda float next to the door of the delivery ship, at a weird upright angle too. This and a few other floating oddities when loading in are presumably a side effect of the "prevent items from falling through the shelf" fix. Can you add a toggle for this?

A few more config toggles in general would be appreciated, even for the small things like the fire exit flip for example. As convenient as it is, I can't help but feel like I'm bypassing an intentional design choice by the dev and I'd love to be able to go back to the way it was without losing the other features in this mod.

**Comment by dragonmcmx1** [comment]
Also a toggle for displaying the total ship loot below the deadline, since I have the Corporate Restructure mod already doing that in a separate monitor.

**Comment by Shaosil** [comment]
All good stuff, I'll have those in the next update 👍🏼

**Comment by dragonmcmx1** [comment]
Many thanks! 🙏

**Comment by Shaosil** [comment]
> This and a few other floating oddities when loading in are presumably a side effect of the "prevent items from falling through the shelf" fix. Can you add a toggle for this?

I will add the toggle either way, but do you happen to recall an example of a specific item that was floating when it shouldn't have been? I had fixed the clipboard and sticky note being rotated incorrectly, but I wonder if there's something I'm overlooking not related to specific items. If you can't remember, no worries.

**Comment by dragonmcmx1** [comment]
> I will add the toggle either way, but do you happen to recall an example of a specific item that was floating when it shouldn't have been? I had fixed the clipboard and sticky note being rotated incorrectly, but I wonder if there's something I'm overlooking not related to specific items. If you can't remember, no worries.

Yeah, the candy / lollipop item for one. Also any gear you order from the store floats when you open the delivery ship. I also had a few instances of gear sitting at a weird angle on the shelf yesterday when I joined a lobby (flashlights were pointing straight up for example rather than lying down), but at the time I didn't know it was this mod doing it, and when I tested it again today by going into some of my own saves I couldn't get it to happen again so maybe there was some other reason that time.

**Comment by NeuTraLZero** [comment]
Just wanna add that items from presents also float and don't drop to the ground

**Comment by Shaosil** [comment]
Got it, I have the fix coded (I was doing something to the items on the ship that affected all items of that type) and the config value added, hopefully I'll get v1.0.14 released later today.

**Comment by Shaosil** [comment]
All fixed in release v1.0.14, which should be live shortly.

**Comment by Shaosil** [comment]
The gifts were still bugged when opening them in the ship - this is ACTUALLY been fixed in v1.0.15, going live now.
