### ISSUE TITLE
[SUGGESTION] Add delivery dropship scan node

### ISSUE THREAD

**Issue by NilaierMusic** [Shaosil/LethalCompanyMods-GeneralImprovements#121]
Simple, but effective little tweak that will add a scan node to a dropship when it lands on the planet and hides it when it leaves. Useful for new players and for moons when it isn't so clear where dropship landed like Vow, March, Rend, Dine and Titan. Should probably be affected by `FixPersonalScanner` so you can scan this node from far away.

**Comment by Shaosil** [comment]
Oh good idea! I'll try to add this by next update.

**Comment by Shaosil** [comment]
Added in v1.1.10, going live soon.
