### ISSUE TITLE
[Question] UseBetterMonitors

### ISSUE THREAD

**Issue by CrazyLBC** [Shaosil/LethalCompanyMods-GeneralImprovements#123]
There is nothing in the descriptions saying what to type into the "ship monitor _" sections to display different items.

What can I type in those boxes to display different things on the monitors?

**Comment by Shaosil** [comment]
The config file (and r2modman) both display the list of acceptable values that can go in those fields. However, if you're using the Lethal Config mod, they do not yet read those values in, so they don't show what the options are.

As of right now, the possible values are:

ProfitQuota, Deadline, ShipScrap, ScrapLeft, Time, Weather, FancyWeather, Sales, Credits, DoorPower, TotalDays, TotalQuotas, TotalDeaths, DaysSinceDeath, InternalCam, ExternalCam

With more being added once in a while.
