### ISSUE TITLE
Keep items on Teleport weight issues

### ISSUE THREAD

**Issue by Slendykins** [Shaosil/LethalCompanyMods-GeneralImprovements#126]
I've got the teleporter set to keep held items but if you have more items that get dropped you keep that weight added after teleporting,

Also wondering if teleport items could have support for ReservedItems by Flip?

Loving the mod, keep up the amazing work!

**Comment by Shaosil** [comment]
I think the weight issue should be fixed in v1.1.10, which is going live shortly.

For the other question, you can try setting the new option for teleporter equipment to "NonScrap"
