### ISSUE TITLE
Can't figure out all configurations from ExtraMonitors.

### ISSUE THREAD

**Issue by callmac** [Shaosil/LethalCompanyMods-GeneralImprovements#127]
I am just wondering what  are all of the configurations I  can set the monitor to display.

**Comment by MaxOhNoo** [comment]
Same, wondering what all the options are.

**Comment by Shaosil** [comment]
I'm not at my PC right now but the config options are listed in the config file itself, as well as r2modman. I'm guessing you are both using LethalConfig which doesn't yet implement the acceptable values, so you won't be able to see what they are in game.

**Comment by MaxOhNoo** [comment]
Thanks!

**Comment by MaxOhNoo** [comment]
@Shaosil Wanted to make things easier for everyone
![BetterMonitors Guide](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/87615947/74e4b8e9-0634-4d8f-9d7d-64045455475d)

**Comment by callmac** [comment]
Thanks, you guys have been a great help.
