### ISSUE TITLE
[Suggestion] Option to change how the profit quota monitor is laid out?

### ISSUE THREAD

**Issue by LocalDunce** [Shaosil/LethalCompanyMods-GeneralImprovements#128]
Right now, when your quota gets into the thousands territory or you sell some scrap, it abruptly switches to taking up four lines instead of three, since it would go off the edge of the monitor otherwise. I was wondering if there could be an option to make it four lines by default, always pushing the amount you have to meet to a fourth line for consistency. Alternatively or additionally, I think an option to display just one number representing how much scrap you still need to turn in to meet quota (fulfilled quota minus actual quota) would also be nice. (Edit: Additionally, it would be nice if there was an option to display a calculation of overtime, perhaps on the quota monitor once you get past the profit quota.)

**Comment by Shaosil** [comment]
I make the profit quota always take 4 lines (if using custom monitor settings) as of v1.2.6, and the overtime monitor is coming eventually :)
