### ISSUE TITLE
[Suggestion] Merging similar monitor mods together 

### ISSUE THREAD

**Issue by julian-perge** [Shaosil/LethalCompanyMods-GeneralImprovements#129]
Hello! I recently released [OpenMonitors](https://github.com/julian-perge/LC_OpenMonitors), and a user recently opened an issue mentioning incompatibility with this mod. I honestly had no idea this mod added monitors! Nice!

Since these mods are pretty similar overall, would you be interested in merging the repos together into their own repo? Something like `GeneralImprovments-Monitors`.

I'm suggesting a separate repo / mod, that way they can be installed separately as necessary, along with then being able to create a `GeneralImprovements ModPack` if you'd like in the future.

Also helps cut down on code in a repo, especially when it comes to configuration options 😅

**Comment by dannycreations** [comment]
#108

**Comment by julian-perge** [comment]
> #108

Thanks for the link, much appreciated!

**Comment by Shaosil** [comment]
Thanks for the suggestion! Unfortunately I'm being stubborn and keeping my monitor code in this singular repo. I know some people want me to move them out but I really just want to maintain code in one place at this time.

Thanks though :)
