### ISSUE TITLE
Starting credits scaling, lacks a critically useful scalar type feature.

### ISSUE THREAD

**Issue by Roobotics** [Shaosil/LethalCompanyMods-GeneralImprovements#133]
Past 4 people, it is very useful to add supplementary credits as we all know. But having less than 4 players, often breaks how this math works unfortunately.

You should still be able to have the 'vanilla' 60 credits with less than 4-players. But with how it is currently, there is only a few ways to set this up, and the main problem is: It **changes** per head-count!

1-player: 
Base: 
60=60

2-player: 
Base + Extra: 
30+30=60

3-player: 
Base + Extra+ Extra: 
30+15+15=60

4-player: 
Base + Extra + Extra + Extra
15+15+15+15=60

5-player: Base + Extra + Extra + Extra +Extra (extra credits desired because past normal player count)
15+15+15+15+15=75

At first it seems like the answer is "Well just make Base and Extra, both 15 then."
But now this config will only give a 2-player session 30 total, instead of the 60 base. 

Consider adding a config option such as: "BaseNumberOfPlayers"
By setting this to 4, (MinimumStartingMoney) could be 60, and anything above that is considered as counting as extra players for the bonus credits. Then there is also flexibility in being able to change it to 2, 3, 8? really as long as the number of players is below the configured 'Base' then no extra credits are needed then.

This relatively simple conditional check, would enable a lot of flexibility for buyables, without overdoing it or underdoing it, with regards to solo-play vs 8-players, etc.

**Comment by Shaosil** [comment]
I'm not sure I totally understand the problem, sorry. Let me try to get on the same page; I have two variables:

StartingMoneyPerPlayer
MinimumStartingMoney

If you wanted the vanilly 60 credits for less than 4 players, you would simply set StartingMoneyPerPlayer to 15 and MinimumStartingMoney to 60.

That way, you would keep the 60 credits until a 5th player joined, at which point you would have 75. Wouldn't that solve your problem?

**Comment by Shaosil** [comment]
I'll go ahead and assume this is working as intended.
