### ISSUE TITLE
[Suggestion] Toggle to have the "ShipMapCam" face "South"

### ISSUE THREAD

**Issue by Fl4sHNoX** [Shaosil/LethalCompanyMods-GeneralImprovements#135]
Could it be possible to have a toggle like this to have the camera face "South" instead of North?

I don't know if it would be better to have both a "ShipMapCamDueNorth" & "ShipMapCamDueSouth" in the config file, or change it to something like "ShipMapCamDueDirection" with "default, north, south" as possible values?

![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/3759901/d5d36b63-2f68-47bd-a153-55ec194b5c92)

> Current config file variable.

The reason I'm asking about it is mainly because of two things:

- The vanilla orientation is closer to having the camera oriented South than North
- I'm using a compass mod ([Solos_Ring_Compass_TWEAKED](https://thunderstore.io/c/lethal-company/p/HectorAlligator/Solos_Ring_Compass_TWEAKED/)) that has the South facing the screens but it doesn't match with the screen orientation:

![ShipMap FacingNorth](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/3759901/668871fc-cf80-4633-a721-da59a75f27f4)

> Edited ShipMap orientation with the "ShipMapCamDueNorth" set to "true".

![ShipMap Vanilla](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/3759901/ca4202f6-a906-4bc9-8313-c48668ebbb74)

> Vanilla camera orientation for reference.

**Comment by Shaosil** [comment]
Added an option in v1.3.3, going live shortly
