### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by apeng0907** [Shaosil/LethalCompanyMods-GeneralImprovements#137]
[Info   :GeneralImprovements] Adding ToggleableFancyLamp behavior to FancyLamp prefab.
[Error  : Unity Log] Panel label not found.
[Error  : Unity Log] Delete file game object not found.
[Error  : Unity Log] Error occurred while refreshing save buttons: Object reference not set to an instance of an object
[Error  : Unity Log] Error occurred while updating files panel rect: Failed to find FilesPanel RectTransform.
[Error  : Unity Log] An error occurred during initialization: Object reference not set to an instance of an object
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type SprayPaintItem and name Awake and parameters

**Comment by Shaosil** [comment]
I just confirmed this still happens in certain mod collections even when disabling GeneralImprovements, so it is unrelated to my info message - it just happens to come directly after it. Closing issue.
