### ISSUE TITLE
Frame Loss - Using DoorPower for Monitors 

### ISSUE THREAD

**Issue by Aeniema** [Shaosil/LethalCompanyMods-GeneralImprovements#138]
(bettermonitors=true) when adding DoorPower to the monitors, when closing ship door after landing (when power drains) greatly decreases frames! Lossing around 100-110 frames when closing door and power drains and updates the monitor.

Time also decreases frames by about 10-15 frames (not that significant)

Only now ever noticed this due to first time using "DoorPower" for monitors.

**Comment by Shaosil** [comment]
Fixed in v1.1.10, going live shortly

**Comment by Aeniema** [comment]
Can also confirm fixed alongside other calculation methods too - thank you so much and great work! <3
