### ISSUE TITLE
[Suggestion] Lightning / electrified item indicators

### ISSUE THREAD

**Issue by throwitaway99** [Shaosil/LethalCompanyMods-GeneralImprovements#14]
I'm not sure if it's out of the scope of the mod nor the feasibility, but a better indication of electrified items (such as specifically highlighting which items are being electrified, perhaps by highlighting the affected slots) would be a very useful feature. If not possible, (or if possible, in conjunction with) some sort of toggle-able on-screen indicator would be nice. I believe there is something like that in the base-game(?), although my modded game certainly doesn't show anything - something that pops on-screen would be nice, perhaps even listing which slots / items are affected.

**Comment by Shaosil** [comment]
I like this tweak idea, I'll plan on doing something like that eventually

**Comment by Shaosil** [comment]
Guess what I finally got around to doing? v1.1.5 is going live shortly :)
