### ISSUE TITLE
Item sales are deterministic when this mod is active

### ISSUE THREAD

**Issue by Hardeh** [Shaosil/LethalCompanyMods-GeneralImprovements#141]
Each time you start a game - you will have exact same 50% shovel sale (or 50% pro flashlight sale if Lategame Upgrades mod is enabled), making item sales deterministic, at least for the first day. Is that possible that sales fix in 1.1.10 affected item sales in some way, or it's vanilla behavior and i just can't see it on host without GE?

**Comment by Hardeh** [comment]
I've just tested in lan mode - it's 100% vanilla behavior, just invisible for host player

**Comment by ChefShenko** [comment]
Hey how did you solve it? I dont want to shovel sale when game starts.

**Comment by ChefShenko** [comment]
> Bir oyuna her başladığınızda, tam olarak aynı %50 kürek satışına sahip olacaksınız (veya Lategame Yükseltmeler modu etkinse %50 profesyonel el feneri satışına sahip olacaksınız), bu da en azından ilk gün için ürün satışlarını belirleyici hale getirecek. 1.1.10'daki satış düzeltmesinin ürün satışlarını bir şekilde etkilemesi mümkün mü, yoksa bu sıradan bir davranış ve bunu GE olmadan ana bilgisayarda göremiyorum mu?

Hey how did you solve it? I dont want to shovel sale when game starts.
