### ISSUE TITLE
Optionally destroy keys on takeoff.

### ISSUE THREAD

**Issue by Erquint** [Shaosil/LethalCompanyMods-GeneralImprovements#148]
I'd love to use the unbreakable keys the mod offers if hoarding them between missions wasn't possible. I suggest adding an option to automatically destroy or otherwise invalidate all keys in the ship by the host, including inventories, upon takeoff.

- Destroying would be the simple option.
- The elaborate approach would be to assign doors and keys a matching hidden unique number on level generation and only allow keys to work with doors that match their number.
  - Either use big numbers or allow the user to set the number range in order to leave a chance that an old key will work on a new mission.
  - Then further down that road it would allow an additional option to choose how many numbers to use per mission in order to have multiple subsets of doors and corresponding keys or scale it off the difficulty metrics.

**Comment by Shaosil** [comment]
Implemented in v1.2.2, uploading shortly
