### ISSUE TITLE
Store bug

### ISSUE THREAD

**Issue by ChefShenko** [Shaosil/LethalCompanyMods-GeneralImprovements#149]
When i started to new game as a host i have always exact same %50 shovel discount.
İ checked other versions and this problem starts after version 1.1.10

Fixed the sales not showing up for the host player until the 2nd day. > That fix causing the problem

**Comment by Shaosil** [comment]
Honestly this sounds like a vanilla bug, I bet it was always happening and just not visible due to the bug not showing sales. I'll check it out sometime

**Comment by Shaosil** [comment]
This is fixed as of v1.2.2, since I made new saves use a random seed instead of always using 0.
