### ISSUE TITLE
Mod Incompatibilities

### ISSUE THREAD

**Issue by Noranecore** [Shaosil/LethalCompanyMods-GeneralImprovements#15]
The following mods have incompatibilities: AdvancedCompany, darmuhsTerminalStuff, CompanyBuildingEnhancements

AdvancedCompany breaks the terminal history function from working properly
darmuhsTerminalStuff breaks cycling through players on the radar through arrow keys
CompanyBuildingEnhancements has its "instant landing feature at the company" feature broken

**Comment by Shaosil** [comment]
1) Fixed in v1.0.16
2) Fixed in v1.0.16
3) I would contact the creator of CompanyBuildingEnhancements as they specifically list that feature doesn't work with AdvancedCompany. I tested it with my mod active (without AdvancedCompany) and it worked.
