### ISSUE TITLE
Lightning indicators as a separate mod 

### ISSUE THREAD

**Issue by bmatusiak** [Shaosil/LethalCompanyMods-GeneralImprovements#150]
i love this mod..  but when i use it with out mods it causes a lot of issues using other mods..

the one feature i believe would be nice as a separate mod would be the lightning indicators.

reason why..  this mod provides things that other mods provides, however other mods are more dedicated into that task.

i do like the all in one approach but i find it hard to manage including this mod with my modpacks.

**Comment by Shaosil** [comment]
Thanks for the feedback! Unfortunately I'm holding to my objective approach of the all-in-one mod, so it's unlikely that I will be separating any of the functionality out. I do try to keep most other options at least configurable and defaulting to off unless I feel it's a bugfix or necessary though. Sorry :)
