### ISSUE TITLE
[Bug] AllowPreGameLeverPullAsClient breaks lever

### ISSUE THREAD

**Issue by MathiusXII** [Shaosil/LethalCompanyMods-GeneralImprovements#151]
"AllowPreGameLeverPullAsClient" allows clients to do the animation, but nothing happens, and the host can no longer pull the lever.

**Comment by Shaosil** [comment]
Is this on the latest version? It works for me but it had this problem the first time I implemented it before I fixed it. It's also possible another mod may be conflicting with the code and causing it as well, any error logs?

**Comment by MathiusXII** [comment]
I'd guess it's a conflict since I have it up to date.

Can't test till my friend comes on this weekend, but I'll try then

**Comment by MathiusXII** [comment]
Just tested and it seems to work now. Thanks

**Comment by MathiusXII** [comment]
Sorry, scratch that. 
Just happened again today.
Host said no errors on his end and there were none on mine either at the time I pulled it.

**Comment by Shaosil** [comment]
Well that's weird. Any chance you have a profile code for me to check out? Also, was the host using GI as well?

**Comment by MathiusXII** [comment]
Yes we both use the same serverside mods

018f3057-9da6-a492-7584-dedcd36d8dcc

**Comment by Shaosil** [comment]
Ok this is fixed, I was able to replicate it by having someone disconnect and rejoin, causing the underlying issue. Going live in v1.2.5 shortly
