### ISSUE TITLE
[Bug] FixPersonalScanner broken

### ISSUE THREAD

**Issue by MathiusXII** [Shaosil/LethalCompanyMods-GeneralImprovements#152]
"FixPersonalScanner" makes RClick do nothing. This shows up in the console...

[Error  : Unity Log] ArgumentException: An item with the same key has already been added. Key: ScanNode (ScanNodeProperties)
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <787acc3c9a4c471ba7d971300105af24>:IL_015A)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <787acc3c9a4c471ba7d971300105af24>:IL_0000)
BetterItemScan.Patches.HudManagerPatch_UI.OnScan (HUDManager __instance, UnityEngine.InputSystem.InputAction+CallbackContext context) (at <e281714c90c342f9a441ab340904ec10>:IL_012B)
(wrapper dynamic-method) HUDManager.DMD<HUDManager::PingScan_performed>(HUDManager,UnityEngine.InputSystem.InputAction/CallbackContext)
UnityEngine.InputSystem.Utilities.DelegateHelpers.InvokeCallbacksSafe[TValue] (UnityEngine.InputSystem.Utilities.CallbackArray`1[System.Action`1[TValue]]& callbacks, TValue argument, System.String callbackName, System.Object context) (at <dbb0ce7b96144bd8bcbcb8b0d765f970>:IL_001B)
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr)

[Error  : Unity Log] ArgumentException while executing 'performed' callbacks of 'Movement/PingScan[/Mouse/rightButton]'

**Comment by Shaosil** [comment]
You are most likely using another mod that modifies the scanner, as this does not happen if you use my mod alone.

**Comment by Shaosil** [comment]
On second glance I notice you are using BetterItemScan. This is not compatible with my FixPersonalScanner setting as they are both modifying similar code. Closing as a known bug.
