### ISSUE TITLE
[Bug] Black screen on hosting world with OpenBodyCams

### ISSUE THREAD

**Issue by MathiusXII** [Shaosil/LethalCompanyMods-GeneralImprovements#158]
Removing GeneralImprovements or OpenBodyCams fixes it.
I get some open body cams errors in the console.
Should this be reported to OpenBodyCams instead?

[Error  :OpenBodyCams] Attempted to create a body cam before static initialization has been completed.
[Error  :OpenBodyCams] This may occur if the save is corrupted, or if a mod caused an error during the start of the game.
[Info   :OpenBodyCams] Creating terminal noun 'bodycam' (BodyCam).
[Info   :OpenBodyCams]   Keyword was not found, created a new one.
[Info   :OpenBodyCams] Creating terminal verb 'view' (View).
[Info   :OpenBodyCams]   Keyword existed, appended nouns.
[Info   : Unity Log] !!!! ENABLING CAMERA FOR PLAYER: Player
[Info   : Unity Log] !!!! connectedPlayersAmount: 0
[Info   : Unity Log] Attached static source to PlayerControllerB MathiusXII
[Info   : Unity Log] Instantiating audio filters for static effect
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Diversity.Player.PlayerRevamp.Update () (at <560dcc7533b64dcab9e9bf1b307db897>:IL_017D)

[Info   : Unity Log] [SS]: Waiting for suits to sync...
[Info   :OpenBodyCams] Camera has been destroyed, recreating it.
[Error  : Unity Log] ArgumentException: The Object you want to instantiate is null.
Stack trace:
UnityEngine.Object.Instantiate[T] (T original) (at <e27997765c1848b09d8073e5d642717a>:IL_003D)
OpenBodyCams.BodyCamComponent.EnsureCameraExists () (at <690cb6f14f0340058fff5c214cf90022>:IL_00A4)
OpenBodyCams.BodyCamComponent.SetTargetToPlayer (GameNetcodeStuff.PlayerControllerB player) (at <690cb6f14f0340058fff5c214cf90022>:IL_0010)
OpenBodyCams.SyncBodyCamToRadarMap.UpdateBodyCamTarget () (at <690cb6f14f0340058fff5c214cf90022>:IL_0013)
OpenBodyCams.SyncBodyCamToRadarMap.Start () (at <690cb6f14f0340058fff5c214cf90022>:IL_0000)

**Comment by Drachoth** [comment]
I also had that issue, I found a work around by deleting a save file and starting fresh

**Comment by Shaosil** [comment]
I _think_ this is an OpenBodyCam issue but I'm not sure why removing GI fixes it. I guess I'll leave this open until it's resolved

**Comment by Shaosil** [comment]
Can you try this again as of v1.2.6? I think I might have fixed it.

**Comment by Shaosil** [comment]
GI and OBC are both making several changes, that will most certainly fix this if it hasn't been already. Closing this for now.
