### ISSUE TITLE
[Suggestion] Fix the cupboard door hitbox

### ISSUE THREAD

**Issue by dragonmcmx1** [Shaosil/LethalCompanyMods-GeneralImprovements#16]
Fix the hitbox of the closet doors so it doesn't keep closing accidentally when you put an item inside.

**Comment by Shaosil** [comment]
That's something I can take a look at. I might be able to configure the size of the colliders, or maybe fix whatever causes it to do multiple actions on one interaction if that's the problem

**Comment by Shaosil** [comment]
The latest version (v1.1.15) has an option HideShipCabinetDoors, which if set to true simply removes the doors. This might be a good workaround for you so I suppose I'll close this bug for now.
