### ISSUE TITLE
[Bug] 1.2.1-2: All items being deleted when loading a save

### ISSUE THREAD

**Issue by FerusGrim** [Shaosil/LethalCompanyMods-GeneralImprovements#161]
Sorry, that was a bit of a mouthful.

I have tested this by playing Vanilla, my modpack, and my modpack sans GI. The only variable that results in this bug seems to be that, if the save was created when GeneralImprovements was enabled, then reloading it will result in all tools and scrap being deleted.

**Comment by FerusGrim** [comment]
I guess this would be a duplicate of https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/issues/124, but unfortunately using MoreItems does not magically introduce a fix, for me. Sadge.

**Comment by FerusGrim** [comment]
Huh. This isn't actually a 1.2.2 issue. I downgraded to 1.2.1 and am still experiencing this bug.

I have tested multiple times that it is General Improvements that triggers it, but I'm not sure why it's suddenly a problem today, when I've never experienced this issue, before.

**Comment by Shaosil** [comment]
Huh. So just to confirm, you use vanilla to make a new save, get some items, then launch with GI and the items are missing after loading in?

**Comment by Strider309** [comment]
To help with pinpointing the bug I've done this test.
Loaded in Vanilla. New Save. Bought a flashlight & walkie. Found Large Axel & Key. Dropped axel & walkie, keeping key & flashlight on me. Returned to Orbit & Quit.
Loaded save in modded. All 4 items were missing.

(I did have other mod's active but this bug started immediately after this mod and only this mod had an update)
(In between the this mod's last version & current version I also enabled quota rollover(no other changes) but unsure if that has any relevance to this bug)

**Comment by Strider309** [comment]
Additional test done. (Game crashed on quitting but dont think it changed result)
Started in modded. New Save. Bought flashlight + walkie. Found Large Axel, Tattered Sheet Metal & Plastic fish. Dropped Axel + walkie on ship. Returned to Orbit & dropped fish, keeping metal and flashlight on me. Then Quit(game crashed upon quitting).
Started save in Vanilla. All 5 items were still on the ship.
