### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by Scarefact** [Shaosil/LethalCompanyMods-GeneralImprovements#163]
Since version 1.2.2+ of the general improvements has been released, it's no longer works on v49. So you have to download manually version 1.2.1 to make it work.

**Comment by Shaosil** [comment]
Interesting. Do any error logs exist?

**Comment by Shaosil** [comment]
I'm going to go ahead and close this as not planned, sorry. I feel like v50 has been out for a while now and my mod is a bit complex to try to also support older versions.
