### ISSUE TITLE
[Feature Request] Don't show "Grab : [E]" if item were not grabbable

### ISSUE THREAD

**Issue by dounai2333** [Shaosil/LethalCompanyMods-GeneralImprovements#164]
I'm requesting this because none of current mods does this, at least I didn't found any.
When you put the item to the company sell desk, you can no longer pick your item back, but the HUD are still telling you that. The same with alive Nutcracker, which make some newbies trying to rob the shotgun from Nutcracker while it's alive, and obviously it's not possible.

The variable are simply ```bool GrabbableObject.grabbable```.

**Comment by Shaosil** [comment]
Implemented in v1.2.4, going live shortly
