### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by TheComicRelief** [Shaosil/LethalCompanyMods-GeneralImprovements#165]
Idk what this is but it shows up in the log
[03:04:08.2654330] [Error  :GeneralImprovements] UnityEngine.Vector3[] Load[Vector3[]](System.String, System.String, UnityEngine.Vector3[])
So far, it hasn't caused any trouble but i just wanted to let you know.

**Comment by Shaosil** [comment]
This is actually just a debug message I accidentally left in because I was in a rush to fix the loading error the last update had introduced. It will be removed in the next update.
