### ISSUE TITLE
[Incompatibility] Weird monitor fonts with Imperium installed.

### ISSUE THREAD

**Issue by broken-usb** [Shaosil/LethalCompanyMods-GeneralImprovements#167]
If you have [Imperium](https://thunderstore.io/c/lethal-company/p/giosuel/Imperium/) installed and Better Monitors is set to "True", the font of the monitors will look weird.

![1966720_20240504212511_1](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/50057556/bc98be1a-1893-4f95-a943-2fa5481009ed)

**Comment by Shaosil** [comment]
Fixed in v1.2.6
