### ISSUE TITLE
[Request] SaveFurnitureState for all furniture

### ISSUE THREAD

**Issue by MathiusXII** [Shaosil/LethalCompanyMods-GeneralImprovements#169]
Any way you could save the position of all other furnitures so that when you buy them they're in the same spot?

**Comment by Shaosil** [comment]
Implemented as an option as of v1.2.6.

**Comment by MathiusXII** [comment]
@Shaosil 
Thanks!
Also there's a bug where it automatically buys it for you as well if you leave and rejoin.
