### ISSUE TITLE
question about this and other mod

### ISSUE THREAD

**Issue by HamedAlmanthari** [Shaosil/LethalCompanyMods-GeneralImprovements#17]
hello. does this mod do exactly what CupboardFix mod does?
https://thunderstore.io/c/lethal-company/p/Rocksnotch/CupboardFix/
also, i have HideClipboardAndStickyNote set to false, but the clipboard and sticky note spawn outside of the ship when i load the save. this only happens when i use this mod. maybe conflict with some other mod? idk.
![Screenshot 2024-01-12 161444](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/133137232/7089948c-29bf-457a-8226-6d03c4dbec3f)

**Comment by Shaosil** [comment]
Hi there!

1) It's not doing _exactly_ what CupboardFix is, but the results may be very similar. One of the fixes I have is to prevent things from dropping to the floor through shelves and furniture when loading a game. As a result, items appear to stay in the cupboard as well.

2) I also saw that clipboard bug myself last night! I'll try to track it down and fix it in the next release.

**Comment by HamedAlmanthari** [comment]
do you think these two mods should be compatible or i should disable one of them? i mean the game works just fine but if one of them doesn't do anything with the other then what's the point yk. obviously i would disable the other mod cause this mod is ESSENTIAL 💀

**Comment by Shaosil** [comment]
Haha, well if it works it works so feel free to leave it as is, but to be honest, because they are doing similar things, I would probably only have one of them enabled. And being the creator of this mod, I'd biased toward it of course :)

**Comment by HamedAlmanthari** [comment]
lmao. but does this mod actually keep stuff on the cupboard on load or it just makes it appear as so (like they're just floating but not actually on the cupboard if that makes sense)?

**Comment by Shaosil** [comment]
It just appears so, they're actually floating... but to be fair, they're never actually on the cupboard in vanilla either. If you move the cupboard they stay floating where they used to be. I might eventually make a fix for that too.

**Comment by HamedAlmanthari** [comment]
that fix would be nice. i'll keep both mods for now. until that mod becomes redundant

**Comment by HamedAlmanthari** [comment]
i disabled FixItemsFallingThrough for the time being. i found it very buggy at its current state. sometimes items on the ship stay floating at the place where the ship starts to land from (high up in the sky).

**Comment by Shaosil** [comment]
> i disabled FixItemsFallingThrough for the time being. i found it very buggy at its current state. sometimes items on the ship stay floating at the place where the ship starts to land from (high up in the sky).

Interesting, I haven't seen that yet in testing/playing but I'll keep an eye out for it. Is that happening in v1.0.15?

**Comment by HamedAlmanthari** [comment]
yes i'm using the latest version

**Comment by Shaosil** [comment]
Ok I'll keep that in mind, thanks. For now, the clipboard/sticky note bug has been fixed in v1.0.16, which should be live shortly.
