### ISSUE TITLE
[Request] [Extra Monitors] Overtime Bonus Monitor. 

### ISSUE THREAD

**Issue by AJAL8000** [Shaosil/LethalCompanyMods-GeneralImprovements#175]
A monitor that says how much Overtime bonus we are going to have.
There isn't one like this currently, but I have seen other mods that show it.

**Comment by Shaosil** [comment]
This is in as of v1.4.0, and fixed as of v1.4.4 (going live soon)

**Comment by AJAL8000** [comment]
Thanks!
