### ISSUE TITLE
Oversight with tooltip transpiler patch

### ISSUE THREAD

**Issue by LoafOrc** [Shaosil/LethalCompanyMods-GeneralImprovements#178]
With [this patch](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/blob/1aabb46b939ab97c59d8e5a5540e6e8a5b4ad963/Patches/PlayerControllerBPatch.cs#L362) you have the game not display the tooltip if the item is not grabbable. 

With recent FacilityMeltdown updates I set `grabbable` to false and also set a custom tool tip (e.g. "[ NEEDS 2 PEOPLE ]" for more requirements to pull the apparatus. This is fine in vanilla because it still shows my custom tooltip but with the patch this tooltip just doesn't appear. This definitely feels like an oversight and has lead many people thinking that meltdown is broken.

As a temporary fix Meltdown undoes this patch, obviously not the best solution. I think the best solution while keeping this patch still in place, would be to also check that customGrabTooltip is empty (which is the default) that way it doesn't immediately break my tooltip. However I am curious on what this solved? I feel like even if it was to communicate that it couldn't be picked up a default "[ CANNOT BE PICKED UP ]" would be better, no?

**Comment by Shaosil** [comment]
Should be fixed in v1.2.7. I didn't even realize there was a custom hover tip because none of the vanilla objects use it from what I can tell
