### ISSUE TITLE
Key usage bug

### ISSUE THREAD

**Issue by michaelgoldenn** [Shaosil/LethalCompanyMods-GeneralImprovements#18]
Using a key causes other items in your inventory to be dropped (and maybe makes an item disappear), and visually keeps the key in your hand permanently afterwards. This happens with fully default settings. I suspect it happens because the key is detected as being dropped, and causes issues with the mod. Let me know if you need help testing/replicating this issue.

**Comment by Shaosil** [comment]
Are you by chance using the BetterTeleporter mod, and did you bring a key through a teleporter? Personally I've only had this happen only when I did that. The shifting around of inventory items does make it much more obvious though.

I use keys pretty often with my mod active and haven't seen this yet apart from that. (Hopefully)

**Comment by michaelgoldenn** [comment]
I'm not using BetterTeleporter. I'll try using binary search on my modlist to see if it's an incompatibility with a specific mod

**Comment by throwitaway99** [comment]
I was able to reproduce this issue.

https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/136512585/b786bc0d-18b1-443e-84fe-be585680c8d7

I am not using any other mods, and I was playing as a host. Upon using a key, and an item shifts into the slot of its place, the key will still appear in hand, whilst the item will seemingly get removed from your inventory despite showing otherwise based on the inventory (and it can be confirmed by the minimap). Here is what happens with multiple items in inventory:


https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/136512585/9c3912df-0142-4d65-b9ac-1bc806abd3d2

**Comment by Shaosil** [comment]
Thanks a ton for the clarification! I'll look into this as soon as I can.

By the way - I assume the minimap mod is the only other one you were using? I doubt it has anything to do with that, I'd just like to duplicate the same environment.

**Comment by throwitaway99** [comment]
I should clarify that I also had LethalDevMode and used it to spawn in the key, whilst I had invincibility enabled for the sake of quick testing - I really should've mentioned this in my initial comment.

**Comment by Shaosil** [comment]
No problem, and man I should have found LethalDevMode earlier! I've been using temp hacks I write myself to make everything the same type of loot when I need to test something but I still have to go find the loot lol.

I'll keep you posted when I get to it 👍🏼

**Comment by throwitaway99** [comment]
This whole thing reminded me of an idea I had around the time you added the moving a two-handed item to first slot feature - and that was a toggle-able feature to have the key automatically go to the right-most slot, so you could dump everything off outside and come back inside w/ the key, without having to worry about manually switching slots to avoid dropping the key. I suppose that could (partially?) brute-force fix this particular issue.

**Comment by Shaosil** [comment]
I was able to find out what the issue was and fix it - v1.0.17 will be going live whenever Thunderstore comes back online :)

**Comment by throwitaway99** [comment]
It seems that the bug has returned(?). I've detailed it in my latest issue. #56
