### ISSUE TITLE
[Bug] SaveShipFurniturePlaces All places furniture back on save reload

### ISSUE THREAD

**Issue by MathiusXII** [Shaosil/LethalCompanyMods-GeneralImprovements#181]
If you fail quota, everything gets removed besides default furniture, but if you leave and enter the save again, it spawns everything back including ship upgrade furnitures.

I wouldn't mind a config feature for saving decor furniture, suits, and upgrades between games, but I don't want my upgrades to carry over.

**Comment by Shaosil** [comment]
Should be fixed in v1.2.8, going live shortly
