### ISSUE TITLE
[Bug] ShowHiddenMoonsInCatalog

### ISSUE THREAD

**Issue by JohnMetroid** [Shaosil/LethalCompanyMods-GeneralImprovements#183]
I have ShowHiddenMoonsInCatalog = Always, but hidden moons aren't showing up on the moon registry.  With LLL 1.2.2 + TerminalFormatter.

**Comment by Shaosil** [comment]
TerminalFormatter is probably overwriting what I'm showing in the moons catalog. If I had to guess, ShowMoonPricesInTerminal also doesn't work, correct?

**Comment by ajsglist** [comment]
Yeah, it's possible I should just pass along a request to show hidden moons via TerminalFormatter.

Unfortunately, I can't test ShowMoonPricesInTerminal -- I already have moon prices displayed via TerminalFormatter
