### ISSUE TITLE
1.2.0 and above wont create config files

### ISSUE THREAD

**Issue by ottocolten** [Shaosil/LethalCompanyMods-GeneralImprovements#187]
Hello, I had GeneralImprovements for a while, and noticed recently that it has stopped creating Config files for version 1.2.0 and above, this is a little annoying since I love to use the better Monitors. And the dropdown menus are so much nicer than typing them out, mostly since i dont remember the names. Any fix to this would be amazing, and I can supply you with anything else that you may need.
Thank you for reading, and have a lovely day!

**Comment by Shaosil** [comment]
This should be fixed in v1.4.4 which is going live soon.
