### ISSUE TITLE
[Problem] The game's not responding

### ISSUE THREAD

**Issue by ttmahik** [Shaosil/LethalCompanyMods-GeneralImprovements#188]
After starting the game appears black screen, even the choice of game mode is not (LAN or ONLINE), just a black screen, then comes out the error "game does not respond". Disabled the GeneralImprovements mod and the game was running smoothly

**Comment by ajsglist** [comment]
You can't skip the "LAN/Online" selection screen for tons of mods.

Don't skip this screen.  Disable the GI option.

**Comment by Shaosil** [comment]
I'm going to add a warning to that setting in the next update but I don't have a fix planned for this - some mods just initialize things in parts that the option lets you skip.
