### ISSUE TITLE
Interaction offset bug

### ISSUE THREAD

**Issue by rootbeer2222** [Shaosil/LethalCompanyMods-GeneralImprovements#189]
basically in the first image it says I can grab the shovel but I actually cant, in the second image with the door if I'm right up to it I cant interact as if its not there because the interaction....node? is physically past the door and this goes with anything directly in front of me.

![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/168264445/f16dfec5-c6d1-4abd-842d-74c8ed10451f)

![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/168264445/04e35fbd-b43a-4c3c-966d-46eae166dcc8)

**Comment by Shaosil** [comment]
Fixed in v1.3.1
