### ISSUE TITLE
[1.0.17] Apparatices float outside ship with FixItemsFallingThrough enabled

### ISSUE THREAD

**Issue by throwitaway99** [Shaosil/LethalCompanyMods-GeneralImprovements#19]
This issue has been present prior to this version, and I have tested this as a host w/ FixItemsFallingThrough enabled (the issue is not present with this option disabled). Upon loading into a save with apparatices on-board, I will see that they are not on-board, and when landing they will both be floating outside the ship. I have provided a video that demonstrates this.

https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/136512585/16cb92bf-7bcc-46f7-a45b-c7f8fb27002a

**Comment by Shaosil** [comment]
Ugh that little bit of code is proving to be trickier than I thought. All I'm basically trying to do is see if things are marked as being on the ship already when they load, and if so, I tell them to stop falling at the place they spawned.

There must be something special apparatuses are doing (probably whatever the clipboard and sticky note were) that causes this. I'll see if I can tweak the "target position" so they can "fall" to wherever they actually spawned.

Thanks for finding all this.

**Comment by Shaosil** [comment]
Figured it out! I fixed it by setting the target position to the local position when it's spawned. Confirmed working whenever I release v1.0.18. I'll close this when it's live (maybe later).

**Comment by Shaosil** [comment]
v1.0.18 going live shortly
