### ISSUE TITLE
[Bug] Masked red eyes appear while killing when MaskedEntitiesWearMasks = false

### ISSUE THREAD

**Issue by MathiusXII** [Shaosil/LethalCompanyMods-GeneralImprovements#192]
^

**Comment by Sourceshard** [comment]
Red eyes will need to be preserved in some way or this error will also appear with GI. Not sure what the solution is.

https://github.com/qwbarch/mirage/issues/68

**Comment by Shaosil** [comment]
This is sort of by design - well at least, I did nothing to prevent the eyes from showing up when the masked latch on, since I enjoyed that. For now I don't plan to fix this.
