### ISSUE TITLE
[Suggestion] Keep equipment in teleporter/inverse teleporter

### ISSUE THREAD

**Issue by NickHam13** [Shaosil/LethalCompanyMods-GeneralImprovements#20]
Title. Ideally teleporter and inverse teleporter should be configurable independently

**Comment by Shaosil** [comment]
I'll add this to my todo list :)

**Comment by SenpaiWeed** [comment]
https://thunderstore.io/c/lethal-company/p/SirTyler/BetterTeleporter/

Look code of this mood and maybe you can in u pack.

**Comment by YoBii** [comment]
Input on this. Some mods let you set a list of items that are kept other mods have options like _DropExceptHeldItem_. The latter I like a lot in terms of balancing and not making teleporters OP.

I set that up for inverse tp so I can only choose one item that I want to bring with me.

_Do I take a flashlight or a walkie talkie? Or do I take a portable teleporter (LGU) so I have a chance to escape from whatever situation I'm gonna find myself in?_

Subject of preference of course.

**Comment by Shaosil** [comment]
Hmm maybe I could do something like NumItemsToKeep and just take the first n items from your inventory. Not sure how I should handle reserved slots from mods in that case though. A single held item would probably be easier.

**Comment by Shaosil** [comment]
Implemented in v.1.1.9, going live soon.

**Comment by NickHam13** [comment]
I do appreciate the update, but I was hoping there would be a way to set it to only tools, and not scrap, as the title says. So I'll reopen this and you can decide what to do with it from there

**Comment by Shaosil** [comment]
Fair enough! I plan on adding a NonScrap option soon, I'll use this (and one other open issue about it) to keep track.

**Comment by Shaosil** [comment]
Added a "NonScrap" option for both teleporters in v1.1.10, going live soon
