### ISSUE TITLE
Half the stuff doesn't load with v55

### ISSUE THREAD

**Issue by BurntFood** [Shaosil/LethalCompanyMods-GeneralImprovements#201]
After {[Debug  :GeneralImprovements] Patching out old spray can random color assignment.} it gets this error.

> [Error  : Unity Log] InvalidProgramException: Invalid IL code in (wrapper dynamic-method) SprayPaintItem:DMD<SprayPaintItem::Start> (SprayPaintItem): IL_0020: ret       
> 
> 
> Stack trace:
> System.RuntimeMethodHandle.GetFunctionPointer () (at <787acc3c9a4c471ba7d971300105af24>:IL_0000)
> MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.GetFunctionPointer (System.Reflection.MethodBase method, System.RuntimeMethodHandle handle) (at <4e2760c7517c4ea79c633d67e84b319f>:IL_0000)
> MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.GetNativeStart (System.Reflection.MethodBase method) (at <4e2760c7517c4ea79c633d67e84b319f>:IL_004D)
> MonoMod.RuntimeDetour.DetourHelper.GetNativeStart (System.Reflection.MethodBase method) (at <4e2760c7517c4ea79c633d67e84b319f>:IL_0005)
> MonoMod.RuntimeDetour.Detour._TopApply () (at <4e2760c7517c4ea79c633d67e84b319f>:IL_0025)
> MonoMod.RuntimeDetour.Detour._RefreshChain (System.Reflection.MethodBase method) (at <4e2760c7517c4ea79c633d67e84b319f>:IL_0149)
> MonoMod.RuntimeDetour.Detour.Apply () (at <4e2760c7517c4ea79c633d67e84b319f>:IL_0053)
> MonoMod.RuntimeDetour.Detour..ctor (System.Reflection.MethodBase from, System.Reflection.MethodBase to, MonoMod.RuntimeDetour.DetourConfig& config) (at <4e2760c7517c4ea79c633d67e84b319f>:IL_02E1)
> (wrapper dynamic-method) MonoMod.RuntimeDetour.ILHook+Context.DMD<MonoMod.RuntimeDetour.ILHook+Context::Refresh>(MonoMod.RuntimeDetour.ILHook/Context)
> (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<MonoMod.RuntimeDetour.ILHook+Context::Refresh>?-1894643694(object)
> HarmonyLib.Internal.RuntimeFixes.StackTraceFixes.OnILChainRefresh (System.Object self) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0000)
> MonoMod.RuntimeDetour.ILHook.Apply () (at <4e2760c7517c4ea79c633d67e84b319f>:IL_0059)
> HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo (System.Reflection.MethodBase replacement) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0047)
> Rethrow as HarmonyException: IL Compile Error (unknown location)
> HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo (System.Reflection.MethodBase replacement) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_005F)
> HarmonyLib.PatchFunctions.UpdateWrapper (System.Reflection.MethodBase original, HarmonyLib.PatchInfo patchInfo) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0033)
> Rethrow as HarmonyException: IL Compile Error (unknown location)
> HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0045)
> HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0095)
> HarmonyLib.Harmony.PatchAll (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0008)
> GeneralImprovements.Plugin.Awake () (at <b6dbe9adf0b447958ed7f9c636f5bd45>:IL_02B6)
> UnityEngine.GameObject:AddComponent(Type)
> BepInEx.Bootstrap.Chainloader:Start()
> UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

Extra monitors are missing and pretty much all the things in the [Fixes] section don't work.
HideShipCabinetDoors doors doesn't work anymore.
Not sure what else is broken.

Hotbar management still works.

**Comment by Skyblade799** [comment]
Can confirm; most things aren't loading in.

**Comment by Shaosil** [comment]
This should be fixed in v1.3.0, going live soon
