### ISSUE TITLE
Teleporter config issues

### ISSUE THREAD

**Issue by Jawzper** [Shaosil/LethalCompanyMods-GeneralImprovements#204]
Hi, I've been really appreciating many of the features in this mod in particular the extra screens. So I am using this mod in an InfectedCompany modpack I've been working on. 

For spicier gameplay it's been set up in such a way that teleportation is the only way to enter the facility (with the InverseOnly mod), so players will spend more time isolated whether they want to or not. So I want to allow players to take anything they want in (including modded items). But they should only be able to bring basic equipment if teleported out, otherwise the whole game mode is trivialised. Unfortunately, this mod's teleporter changes don't seem to work very well at present AND they conflict with any other mod I add to change teleporters. 

Firstly the conflict is a big issue for me so... please... add a config toggle to entirely disable any changes to teleporters. This is the easiest solution for me, then I can use a mod which specifically focuses on teleporters with more options. I have seen this suggested before and your answer was to add the NonScrap option which is not the solution IMO. I want to be able to stop your mod from doing ANYTHING to teleporters in case I want another mod to handle this. Please! More generally, "don't interfere with that" toggles are the best way to prevent conflicts for a big mod like this one, so I think adding them for all features would be a huge upgrade. But the teleporters are the big problem for me.

Secondly, it appears that the NonScrap option for the KeepItems configs do not respect some modded items. For example, the pile of glowsticks from AbandonedCompanyAssets which are bought from the store. This is likely an issue with the modded items themselves, but being able to whitelist or blacklist modded items would be appreciated as a workaround for this scenario. As it stands it appears my only option with this mod is to use the All items configuration which is NOT ideal, because...

Thirdly, currently it seems like the config option KeepItemsDuringInverse is completely ignored. Inverse teleporters use the config value for KeepItemsDuringTeleport instead, so it is impossible to have different settings for the Teleporter and the Inverse Teleporter. Combining this with the second issue, for me this is almost game breaking.

So, now I'm stuck in a situation where my players can't inverse teleport with the equipment they want unless I allow them to teleport back to the ship with everything, which completely trivializes InfectedCompany gameplay. As a workaround I will propose a gentleman's agreement with my players to simply not use the regular teleporter, but we miss out on a lot of potential shenanigans this way.

**Comment by Shaosil** [comment]
I fixed the bug with KeepItemsDuringInverse in v1.3.0, going live shortly, and technically if you leave both options on "None", no code changes should occur which should allow compatibility with any other teleporting mods. Once the new version is live can you please confirm it works that way?

**Comment by Jawzper** [comment]
I have just tested with LethalUtilities handling item teleportation and can confirm it's behaving as expected now. Thanks
