### ISSUE TITLE
[Issue] Items misaligned from shelves in cabinets 

### ISSUE THREAD

**Issue by toothbytess** [Shaosil/LethalCompanyMods-GeneralImprovements#207]
I'm not playing with any other mods other than this one and some cosmetics for more company. For some reason since the update, items have been slotting under their respective shelves in the cabinet rather than above them - these flashlights are on the top two shelves for reference. 

![image](https://github.com/user-attachments/assets/78026cdb-2440-44a3-861b-493f69c9e5ff)

I disabled the mod and launched again and the issue stopped. It's also not a problem in vanilla. I've tried changing settings related to the cabinet and it hasn't done anything.

**Comment by toothbytess** [comment]
Update - we've found if we put items in from underneath, they go on top of the shelves. So maybe they're inverted? Still misaligned.

**Comment by Shaosil** [comment]
Does this still happen if you disable the FixItemsFallingThrough config setting?

**Comment by SmoothMemes22** [comment]
This also happens to me, I have all of the settings related to items disabled entirely! I was wondering why the items would bug out like this.

**Comment by toothbytess** [comment]
Yup, I've tried disabling and enabling that setting a few times on fresh saves each time, going to the company building and buying some walkies with the starter cash to test just in case any bugs were holdover. Issue still persists.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Shaosil** [comment]
Fixed in v1.3.5
