### ISSUE TITLE
[Suggestion] Absorb Corporate Restructure Mod

### ISSUE THREAD

**Issue by darkbrewery** [Shaosil/LethalCompanyMods-GeneralImprovements#21]
I noticed your most recent addition conflicts with this other mod: https://thunderstore.io/c/lethal-company/p/Jamil/Corporate_Restructure/
However it looks like the text alignment could be improved anyway, so I'm willing to switch.
Also.. could new features be disabled by default so we don't have to turn them off in config as they are added?
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/806316/ef12f2dd-a3d5-41ac-899d-b794a60bc98e)

**Comment by Shaosil** [comment]
Does it still conflict if you disable the extra monitors?

And hmm. I hear you about disabling things by default, and I'm sure others would like that too, but I imagine there's also a big group of people getting this mod who want all the new features on by default. I'll have to think about this.

**Comment by dragonmcmx1** [comment]
I think I'd agree with having new features off by default, or at least the ones that majorly alter vanilla gameplay (such as the recent suggestion to have the teleporters keep your items during teleport).

Some of my friends I play with get their mod profile from me pre-configured, and it can be hard to keep up with the frequent updates especially if they add/change something major or create conflicts with other mods.

**Comment by Shaosil** [comment]
Sure, so far I've been leaving new features off if they change too much but of course which ones do that are open to debate. For example, I left off the one that would make tools not hit by lightning. But I'll try to default more to disabled if it adds something major like the monitors.

**Comment by darkbrewery** [comment]
I ran into a bug too with the scan fix feature messing with holdtoscan mod, took a while to locate as it was enabled with the new update

**Comment by darkbrewery** [comment]
> Does it still conflict if you disable the extra monitors?
> 
Disabling does not conflict anymore, the above screen is the result of disabling while the other mod was in use.

**Comment by Shaosil** [comment]
I fixed a softlock issue related to Corpoate Restructure mod when orbiting in v1.0.18. I'll keep in mind default disabling for future changes, depending on what they are. Thanks for the feedback!
