### ISSUE TITLE
[Bug] Unable to sell scrap

### ISSUE THREAD

**Issue by broken-usb** [Shaosil/LethalCompanyMods-GeneralImprovements#211]
## Unable to sell anything when SellCounterItemLimit is set to 999

v1.3.5 added the option to increase the ammount of stuff that can be placed at once on the Company's counter to a maximum of 999, the issue is that setting it to 999 prevents you from placing anything in the counter.

https://github.com/user-attachments/assets/4d78cb0e-06bf-4474-b272-3e30f639b775
(Sorry for the black screen at the start, my OBS settings are kinda scuffed atm, video plays normaly after 0:08)

It could be an issue with another mod i have installed but the issue only started happening after the recent update (v1.3.5)

Profile code: `0190f15a-212d-57b0-d34e-7a6ec78fc192`
Log: 
[LogOutput.log](https://github.com/user-attachments/files/16397362/LogOutput.log)
(The log is pretty extensive since i did play for a while before going to sell the scrap, line 4772 is when i pull the lever to land on Gordion)

**Comment by Shaosil** [comment]
Hmm that's an annoying one, sorry if that's mine. I don't see any errors in the log and the code looks ok at a glance so I'll have to test this one. It works if you set it to something like 998, or 100, or 12?

**Comment by Shaosil** [comment]
Nevermind I figured it out... the IL opcode only goes up to 127, so I'll have that fixed in the next update. Setting it from 1-127 should work :)

**Comment by broken-usb** [comment]
> Hmm that's an annoying one, sorry if that's mine. I don't see any errors in the log and the code looks ok at a glance so I'll have to test this one. It works if you set it to something like 998, or 100, or 12?

I tested with 12 and it works fine.

**Comment by Shaosil** [comment]
Fixed in v1.3.6
