### ISSUE TITLE
[Minor Bug] Config Generation Bug

### ISSUE THREAD

**Issue by broken-usb** [Shaosil/LethalCompanyMods-GeneralImprovements#219]
When first installing the mod without its config file, an exception will be printed in the console.
This isn’t a major issue since the mod still manages to create the config file after the exception, and once the config is created, the exception no longer appears.
This seems to have started with version 1.3.6, though I'm not entirely sure.

**Comment by Shaosil** [comment]
This should be fixed in v1.4.4 which is going live soon.
