### ISSUE TITLE
[Suggestion] Fix for the terminal text overlay

### ISSUE THREAD

**Issue by BakaTekku** [Shaosil/LethalCompanyMods-GeneralImprovements#22]
When using view monitor, typing the next command will not show unless you scroll down or exit/reuse the terminal.
this is a vanilla problem but would be nice to have a fix for this.

https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/28825262/840e5074-814d-4dbe-877b-840639752e3f

**Comment by Shaosil** [comment]
That terminal code is a special little snowflake world lol but I'll make a note of this 👍🏼

**Comment by BakaTekku** [comment]
that it is lol thanks I appreciate it.

**Comment by Shaosil** [comment]
v1.2.4 is going live shortly and has a new option: ShowBlanksDuringViewMonitor. If set to false, it should use the behavior you expect.
