### ISSUE TITLE
[Bug] Updating brakes better monitors

### ISSUE THREAD

**Issue by MrMirajIzHere** [Shaosil/LethalCompanyMods-GeneralImprovements#220]
i updated from version 1.3.6 to 1.4.0, and it broke some monitors when not using "add more better monitors", also when i first loaded the game, previously set monitors were in different places
video to show it better:
https://youtu.be/yNOlFn8C3Rg

**Comment by FormSans** [comment]
Yep, and what says monitor 9-14 (Minus the main one) doesn't show ANYTHING but their numbers, even if I have the entire monitor Config list filled.

**Comment by Shaosil** [comment]
Fixed in v1.4.1
