### ISSUE TITLE
[Incompatibility] Game breaking bug with Corporate Restructure

### ISSUE THREAD

**Issue by YoBii** [Shaosil/LethalCompanyMods-GeneralImprovements#23]
Since the latest update this mod in combination with Corporate Restructure mod will break the game. Removing either one resolves the issue.

Of course you're both adding displays above the monitor but even when your newest additions are disabled in config it will produce a null reference error during camerapatch when the round ends after taking off. The ship will never enter orbit and softlocks. 

I can provide the exact error log if you need it.

First I assumed `ShipMapCamDueNorth = true` was the culprit because of **camera** patch but as far as I can tell it doesn't matter.

**Comment by Shaosil** [comment]
Yikes thanks for the heads up! I'll diagnose this later

**Comment by Shaosil** [comment]
I found the softlock issue and will release the fix as soon as I can.

**Comment by Shaosil** [comment]
Fixed in v1.0.18, which should be live shortly
