### ISSUE TITLE
[Suggestion] Add quick drop feature

### ISSUE THREAD

**Issue by darkbrewery** [Shaosil/LethalCompanyMods-GeneralImprovements#25]
By spamming G, drop all items in inventory quickly
Since GeneralImprovements already handles similar inventory management.

Would help reduce mod overhead by not requiring this one: https://thunderstore.io/c/lethal-company/p/Nases/Quick_Drop/source/

**Comment by darkbrewery** [comment]
Additionally, could expand on it by allowing players to sell all items quicker at the company by spamming E

**Comment by GliitchedEntity** [comment]
The problem with quick item drop is, if you drop items too fast as a client, it won't be registered by host and items will desync.
There should be some sort of delay to prevent this, at least in multiplayer. https://github.com/ness77/Quick_Drop/issues/1
I like how General Improvements allows me to drop items right now. I just switch to first slot, spam G, and it allows me to drop the items with just a little delay without causing desync, but still much faster than dropping manually.
Furthermore, I would say, you could keep the delay, but make it when dropping an item, it would switch to the next non-empty slot. For example, if dropping an item in 4'the slot, it will switch to the first slot which have an item.

**Comment by Shaosil** [comment]
Actually this mod already allows rapid E selling at the company! And if you have RearrangeOnDrop on, spamming G will drop everything in your inventory quickly, provided you're on slot 1 when you start. I _probably_ won't expand too much more than it already is as far as that's concerned at least.

Thanks for the suggestion though!

**Comment by darkbrewery** [comment]
Well see the issue is that I had to disable a few of the re-arrange features as they messed with the reserved item slots mod. If there was a way to exclude specific item names ex: flashlights/walkies/etc then that would be super dope.

**Comment by darkbrewery** [comment]
Excluding specific items could be a great work-around for additional mods, some people opt for advanced company which has it's own item slots, haven't tried it but imagine it's the same issue

**Comment by Shaosil** [comment]
Ah, are you on the latest version? I spent some time making it work with both the ReservedItem and AdvancedCompany mods, and it no longer shifts special items around. Unless they broke something since then :)

**Comment by darkbrewery** [comment]
Dude that's awesome 😎 Ill test it out tomorrow, much appreciated, knocks another bloat mod off the list!

**Comment by darkbrewery** [comment]
Also thankyou for increasing saved item limit, that has also depreciated Drakorle-MoreItems-1.0.2
