### ISSUE TITLE
[Suggestion] Add config option for minimum starting credits

### ISSUE THREAD

**Issue by anon-cfg** [Shaosil/LethalCompanyMods-GeneralImprovements#28]
I like your option StartingMoneyPerPlayer, but when setting it to an option like 15, to match vanilla of 60 credits in a 4 person lobby, it has the consequence of leaving solo players with only 15 credits to start with, (or 30 at your config)

It would be nice to have an option to set the minimum amount of starting credits, so if after doing the above calculation on credits per player, if the value is below the minimum, it gets set to the minimum.

Example, I set the following:
StartingMoneyPerPlayer = 15
MinimumMoney = 60

This would result in:
1 player: 60 credits
2 players: 60 credits
3 players: 60 credits
4 players: 60 credits
5 players: 75 credits
6 players: 90 credits

Love the mod, and thank you for considering my suggestion

**Comment by Shaosil** [comment]
You got it! Will be in next release.

**Comment by Shaosil** [comment]
Added in v.1.0.20 which is going live shortly.
