### ISSUE TITLE
[Suggestion] Add config settings to hide weather on weather monitor

### ISSUE THREAD

**Issue by Hardeh** [Shaosil/LethalCompanyMods-GeneralImprovements#29]
We like to play with hidden weather, but still might want to see other additional monitors, so maybe, if possible, add config option to show custom text or "unknown" instead of weather?

**Comment by Shaosil** [comment]
Good call, I'll add settings for each monitor.

**Comment by Shaosil** [comment]
Added in v.1.0.20 which is going live shortly.
