### ISSUE TITLE
Partial incompatibility with Touchscreen mod

### ISSUE THREAD

**Issue by NilaierMusic** [Shaosil/LethalCompanyMods-GeneralImprovements#33]
Using two different configurable functions from [GeneralImprovements](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements) mod, causes a couple of visual bugs with [Touchscreen](https://github.com/TheDeadSnake/LC-Touchscreen) mod by [TheDeadSnake.](https://github.com/TheDeadSnake)

Option `AddTargetReticle` when set to `true` causes [Touchscreen's](https://github.com/TheDeadSnake/LC-Touchscreen) cursor to disappear when hovering over the monitor, instead being replaced by the faint Target Reticle that GeneralImprovements adds.
![IMG_20240117_015214](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/86863646/6720882b-c39b-482c-a728-cef675b67ea9)

Option `ShipMapCamDueNorth` when set to `true` causes [Touchscreen's](https://github.com/TheDeadSnake/LC-Touchscreen) labels to be displaced from their intended position, although the intended behavior of closing the door, disabling landmines and turrets still works, you need to click on the object itself instead of the label, which is really confusing.
![IMG_20240117_014426](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/86863646/8abe6656-7be0-4015-a6a4-d12040633db7)

Both of these visual bugs don't cause any errors in the console, since intended functionality of both mods doesn't completely break, but the visual part partially does.

**Comment by Shaosil** [comment]
The labels being off center should be fixed in v1.0.21, which is going live shortly. I'll look in to the cursor problem soon.

**Comment by NilaierMusic** [comment]
Okay, offset is a bit less now, but isn't completely accurate. If you're interested, seed is 67907704, Experimentation. This is a landmine straight at the end of the center corridor on the main entrance. You can tinker with x and y values for labels (if that's how you partially fixed the offset issue) and compare them to the screenshots by using something like [LCSeedPicker.](https://github.com/FlooflesDev/LCSeedPicker)
![30_20240117114803](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/86863646/8db21484-3c86-4965-b41a-f53f04daf241)

**Comment by Shaosil** [comment]
I think you win the award for most detailed screenshots lol, thanks! I'll tweak it for the next release. Good to know about the seed picker too.

**Comment by NilaierMusic** [comment]
So, i've cloned the project and tried different values for `mapRadarText.rectTransform.pivot` 2d vector. Original values of `0.5f, 0.5f` are almost fine, but if we put y as 0 (`0.5f, 0f`) we get almost the ideal placement. It just looks like collision boxes for interaction with mines and doors (haven't tried turrets) are a bit different, so even with a good placement, not every label is exactly perfect. But, it's probably an issue with the [Touchscreen's](https://github.com/TheDeadSnake/LC-Touchscreen) mod itself, so there's not much we can do.

**Comment by Shaosil** [comment]
Interesting. I tried bumping the position data of the labels after rotating them and got it close to vanilla, but you might be right about the hitboxes.

Anyway, the topics in this issue should be fixed as of v1.0.22, which is going live shortly.
