### ISSUE TITLE
[Compatibility] Quota rollover triggers advanced company XP gain each time you take off if your quota is full

### ISSUE THREAD

**Issue by Hardeh** [Shaosil/LethalCompanyMods-GeneralImprovements#35]
Normally, you should gain XP only once you switch to the next quota.
According to advanced company developer, PotatoePet:
"SetNewProfitQuota
The game calls that when it wants to set a new profit quota after the quota was finished
Thats when I grant XP
He can add a [HarmonyBefore(new string[]{ "AdvancedCompany" })] and fix it
or increase its priority"
Is it gonna be possible to fix?

**Comment by Shaosil** [comment]
So the base game is actually what is calling SetNewProfitQuota each time the ship leaves, if it detects the current funds are greater than the target profit quota. I actually already check for that in my code, and prevent further execution of base game code if there are still remaining days.

I don't think changing the priority of my prefix hook will fix this - I believe it would be up to PotatoePet to check something like this before applying XP, if he is basing it off a call to SetNewProfitQuota:

```
if (TimeOfDay.Intsance.timeUntilDeadline > 0)
{
    // Cancel out however it makes sense
    return false;
}
```
