### ISSUE TITLE
Error with Advanced Company new update

### ISSUE THREAD

**Issue by ChooMcoo** [Shaosil/LethalCompanyMods-GeneralImprovements#38]
Advanced Company released a new update removing a lot of their interactions with the ship terminal and I've been told this mod tried to do some patching with it before. Now when I open Advanced Company's portable terminal and select the item quantity in the store this error gets thrown

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GeneralImprovements.Patches.TerminalPatch.Update (Terminal __instance) (at <fe3c77c8ae7b4c04bb669a4ec4a30364>:IL_01BD)
(wrapper dynamic-method) Terminal.DMD<Terminal::Update>(Terminal)

Though once I open the big terminal and open up the portable terminal after and do the exact same thing no more error. I can consistently reproduce this.

**Comment by Shaosil** [comment]
Quick clarification on this since I don't use AdvancedCompany yet - what do you mean by portable terminal? Is it something to purchase?

**Comment by ChooMcoo** [comment]
The portable terminal is something everyone has access to by default via a keybind. It pulls a handheld device up yo your face that allows you to assign perks, extend the deadline, and access the terminal store without using the big on on the ship. He has it set up so instead of typing a name and quantity for items, you hit the arrow keys or wasd to scroll through the item list and increase or decrease the quantity. When increasing and decreasing the quantity in the portable terminal that error is thrown. Though once I open the main terminal for the first time, and go back to the portable terminal and increase or decrease the quantity on an item the error is no longer thrown.

**Comment by ChooMcoo** [comment]
After doing the aforementioned "fix" with opening the main terminal then going back to the portable one, your mod now prints this info text every time I change the quantity which of course if fine. Just wanted to mention in case it helps
[Info   :GeneralImprovements] CUR NODE: Start
[Info   :GeneralImprovements] CUR TERMINAL TEX: shipScreen1
[Info   :GeneralImprovements] CUR PERSISTENT TEX:

**Comment by Shaosil** [comment]
Ok this seems to be fixed in the release I'm working on locally when testing with your profile. I might have inadvertantly fixed it when fixing something else. I'll update here when it's going live.

**Comment by Shaosil** [comment]
v1.0.22 should be going live shortly. Let me know if this is still happening and I'll reopen the issue.
