### ISSUE TITLE
Incompatibility with AdvancedCompany

### ISSUE THREAD

**Issue by OnlyJe** [Shaosil/LethalCompanyMods-GeneralImprovements#40]
The slot tweaks (PickupInOrder, RearrangeOnDrop, and TwoHandedInSlotOne) is not working with AdvancedCompany enabled

**Comment by Shaosil** [comment]
This is known, see [here.](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/issues/7#issuecomment-1885299617) Advanced Company does too much with inventory management and we would just step on each other if I tried to keep those features in, sorry.
