### ISSUE TITLE
Partial incompatibility with Corporate Restructure + suggestion

### ISSUE THREAD

**Issue by NilaierMusic** [Shaosil/LethalCompanyMods-GeneralImprovements#41]
I like the new weather monitor in GeneralImprovements, but all of the other monitors and more are already kind of implemented in [CorporateRestructure](https://thunderstore.io/c/lethal-company/p/Jamil/Corporate_Restructure/) mod. It would be cool to have a config option to move certain monitors to the other positions and maybe remove the blue background in them for more vanilla-like experience.
![IMG_20240118_053909 (1)](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/86863646/994ab4da-c464-4cb0-a17e-1702ce6894c6)

**Comment by Shaosil** [comment]
I agree it needs to be more customizable. When I get around to creating the other monitors and have easy references to their positioning and stuff, I'll try to make them more configurable. Putting this on a (hopefully short) backlog for now.

**Comment by Shaosil** [comment]
I went ahead and took care of this when I restructured the config in v1.0.23.
