### ISSUE TITLE
Medical station not showing

### ISSUE THREAD

**Issue by Bornnemissis** [Shaosil/LethalCompanyMods-GeneralImprovements#42]
have the setting set to true and still doesn't show, there anything else besides the dll that needs to be in plugins?

**Comment by Shaosil** [comment]
Yeah you'll need the assets file as well, if you did a manual install from github you can find that in the releases section

**Comment by Bornnemissis** [comment]
> Yeah you'll need the assets file as well, if you did a manual install from github you can find that in the releases section

gotcha, now my issue is it wants me to rename it because I have a folder named assets

**Comment by Shaosil** [comment]
Yeah it should auto detect it if you put it in the same location as the DLL, so just put the DLL and assets file in a subfolder

**Comment by Bornnemissis** [comment]
ahh yup that worked haha thanks for that
