### ISSUE TITLE
[Suggestion] Keybind to override collision while in ship build mode

### ISSUE THREAD

**Issue by dragonmcmx1** [Shaosil/LethalCompanyMods-GeneralImprovements#43]
First of all, thank you once again for the frequent and reliable updates, fixes and additions. Very happy with the new config that came with the latest version!

Today's suggestion is to add a keybind when placing ship/decor objects that overrides collision with other ship objects (as well as ship walls maybe to some extent), allowing you to place objects such as teleporters inside of each other with no restrictions. There are two other ship placement overhauls and neither of them seem to get this right.

**Comment by Shaosil** [comment]
Hmm that sounds like it will either be trivial or overcomplicated lol. I'll keep this on my list though and see how it goes.

**Comment by Shaosil** [comment]
I didn't add a keybind for this however I did add an option in v1.2.4 which is going live shortly, called ShipPlaceablesCollide. If you set that to false it should do what you want.
