### ISSUE TITLE
Quota Rollover causing deadline to freeze if you complete more than 1 quota

### ISSUE THREAD

**Issue by Re-VelatoR** [Shaosil/LethalCompanyMods-GeneralImprovements#49]
As title says. Friend and I sold around 800 on the very first quota for supplies and Rend money. Rend runs following ended up not reducing the days left until deadline.

**Comment by Shaosil** [comment]
Are you by chance using any other quota rollover mods? I haven't seen this myself with mine (yet) and we have done a few runs where we stayed past quota. I did see that problem with other quota rollover/deadline extender mods though.

It could certainly be a problem with mine, just trying to narrow it down first.

**Comment by Re-VelatoR** [comment]
I am not. We do have a mod that allows us to purchase additional days, but we have not done that yet as this issue happened on the very first quota.

**Comment by Shaosil** [comment]
Gotcha. I'll take a look and do some deeper testing with this.

**Comment by Shaosil** [comment]
Any chance you still have the log file? An exception could have prevented time from passing if I missed something.

**Comment by Re-VelatoR** [comment]
Probably not. I'll replicate the issue tomorrow morning and see if it occurs and what it says.

**Comment by Re-VelatoR** [comment]
So I tested it out. This mod doesn't seem to be throwing an error, nor does ExtraDaysToDeadline, but it IS however, incorrectly setting the remaining days to 3 because THAT mod doesn't seem to properly recognize quota rollover mods and compensate for them. I will report this issue there as well.

**Comment by Shaosil** [comment]
Gotcha - that seems like an oversight on the extra days mod, my mod isn't actually setting the remaining days anywhere, that's happening in base game code. I'll mark this as closed for now, thanks for helping look into it.
