### ISSUE TITLE
[Compatibility] Can't leave moon on E Gypt

### ISSUE THREAD

**Issue by Easyidle123** [Shaosil/LethalCompanyMods-GeneralImprovements#50]
With GeneralImprovements installed it seems that I can't leave the E Gypt moon. Other LethalLevelLoader-dependent mods like Atlas Abyss let you leave, so it seems to be a problem between E Gypt and GeneralImprovements specifically. The E Gypt dev is aware of this and multiple other people have reported the problem to them, but I don't think anyone's tracked down what the issue is being caused by yet. You can pull the lever, but the ship won't take off and will be stuck on "waiting for ship to land". This is on the latest version of E Gypt + all dependencies and GeneralImprovements + all dependencies, but seems to have been a known issue for a week or two.

**Comment by Shaosil** [comment]
Hmm interesting, I'll check this out when I can

**Comment by Shaosil** [comment]
Found the problem - will be fixed in next release.

**Comment by Shaosil** [comment]
Fixed in v1.0.25, going live shortly.
