### ISSUE TITLE
No  Health recharge station

### ISSUE THREAD

**Issue by Kayotik16** [Shaosil/LethalCompanyMods-GeneralImprovements#52]
when checked no recharge station is there. is there any incompatibilities I'm not aware of?

**Comment by Shaosil** [comment]
Just to be sure, did you set the AddHealthRechargeStation to true after the last config overhaul? You may still be seeing AllowHealthRecharge or whatever it was called, which is no longer used

**Comment by Shaosil** [comment]
To add on to this, as of v1.0.25 this is a host required setting, meaning clients will only see the med station if the host also has the AddHealthRechargeStation setting set to true. Let me know if you still run in to problems though and I'll reopen this.

**Comment by Kayotik16** [comment]
> To add on to this, as of v1.0.25 this is a host required setting, meaning clients will only see the med station if the host also has the AddHealthRechargeStation setting set to true. Let me know if you still run in to problems though and I'll reopen this.

sorry for late response just got back home, i was on v 1.0.23 i have not tested this as of latest update, i will get back to you if i still do not see it

btw yes i did do everything you mentioned above i think the newest version may have fixed this
