### ISSUE TITLE
[Suggestion] Add the ability to disable the external camera monitor

### ISSUE THREAD

**Issue by ViLiDi230** [Shaosil/LethalCompanyMods-GeneralImprovements#53]
I suggest adding a setting that allows you to turn off this monitor, or add the ability to change the background color of monitors (because blue stands out too much against the background of other monitors)
![Снимок экрана (1739)](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/99673250/247ac500-259a-45a1-886e-10edc3fff97d)
![Снимок экрана (1740)](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/99673250/0a2d9cff-1c48-4469-8da7-6348314723aa)
![Снимок экрана (1743)](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/99673250/5e443628-6fe1-4c83-b51f-b9ac6ca9749b)

**Comment by Shaosil** [comment]
All monitors are now fully customizable when v1.1.0 goes live (shortly)! Just set UseBetterMonitors = true and play around with the numbered items underneath.
