### ISSUE TITLE
Scannable Tools in lethal config

### ISSUE THREAD

**Issue by CatsArmy** [Shaosil/LethalCompanyMods-GeneralImprovements#55]
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/104517593/949dc5c4-310e-4443-9818-9dd88f7eebb4)

i have a simple fix for this i will in a moment create a pr

**Comment by Shaosil** [comment]
I actually have this fixed locally, thanks though! Someone pointed out it wasn't working and I caught a dumb mistake I made lol

**Comment by Shaosil** [comment]
I'll probably have another update pushed later

**Comment by CatsArmy** [comment]
o
well there goes an hour of my life lol haha rip
its 12:33 painnnnnnn
welp at least its fixed i guess lol

**Comment by Shaosil** [comment]
Haha sorry!! I know the feeling 🙏 thanks for putting effort into it. I'll update this issue when I release it

**Comment by CatsArmy** [comment]
It's fineee lul

**Comment by ChloeDawn** [comment]
To add to this, FYI your current implementation does not account for the "All" option, it only looks for exact type name matches

**Comment by Shaosil** [comment]
> To add to this, FYI your current implementation does not account for the "All" option, it only looks for exact type name matches

Indeed, that was the main problem! I was also incorrectly generating the description for the config file - both of those are now fixed in v1.0.26, going live shortly.
