### ISSUE TITLE
Objects being picked up on scanner when they shouldn't be

### ISSUE THREAD

**Issue by ButteryStancakes** [Shaosil/LethalCompanyMods-GeneralImprovements#57]
Ever since the rework of the FixPersonalScanner setting I've noticed the scanner being overly sensitive and detecting a lot of stuff it shouldn't be, which makes it a little less useful due to visual clutter.

Although the issue with items being scanned in your inventory was fixed, items that other players are holding will still be displayed, including items they have pocketed. If this behavior is intended, I would appreciate it being made into a config setting, since I'd rather only see stuff that other players haven't already found. Also I don't think it makes much sense to display other players' unequipped items at all, but that might also make sense as a configurable.

Additionally, I've noticed that opened code doors are still showing the blue "Secure door" prompt, which doesn't happen in vanilla to my knowledge - if it does, I've never noticed. Disabling that as well would be nice, since I'm generally using the scanner to catch out snare fleas in the doorway, and the tooltip is unnecessary when the door is already opened.

**Comment by Shaosil** [comment]
It's definitely not intended to show unequipped or hidden items, I'll have to verify how I'm handling the scan code. I'll also turn the "held items" from other players into a config setting.

For the doors, I'll fix that but I'm also curious if it's in vanilla, it could be either lol. Either way, thanks for the heads up.

**Comment by Shaosil** [comment]
Actually I just wasn't taking disabled scan nodes into account - in the next release it will be, which fixes all of the described issues. I'll update this issue when it goes live.

**Comment by ButteryStancakes** [comment]
Sounds great. I appreciate your help, again :)

**Comment by Shaosil** [comment]
v1.0.27 is going live shortly, closing this for now.
