### ISSUE TITLE
Monitor Position 6 is split

### ISSUE THREAD

**Issue by VanilaBOI** [Shaosil/LethalCompanyMods-GeneralImprovements#59]
Only the top left half of the the Screen displays the Text.
![20240121233921_1](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/86358160/ddc62e02-623f-4f52-8104-44c9bc76957b)

**Comment by Shaosil** [comment]
Fixed in v1.0.27 which is going live shortly.
