### ISSUE TITLE
compatibility issue with ReservedItemsllot

### ISSUE THREAD

**Issue by Bornnemissis** [Shaosil/LethalCompanyMods-GeneralImprovements#6]
when used with the mod reserveditemslot for flashlight and walkie it will pull the items off the alt reserved bar as well

**Comment by Shaosil** [comment]
Hi there,

Yeah, I'm actually aware of that issue and sadly I can't do much about it without being able to hook in to the ReservedItemSlot mod, at least from what I can tell.

At one point I fixed it, but it completely broke any mods that add extra slots (see issue #1) Without getting too technical, it's one or the other at this time, and your best bet is to disable the RearrangeOnDrop config setting. Sorry!

**Comment by Shaosil** [comment]
Actually you know what I'll try to look deeper into this and see if there's anything fancy I can do to detect it.

**Comment by Bornnemissis** [comment]
gotcha, just wasn't sure if you were aware since the newest update but I use both regardless it's pretty useful I appreciate the mod.

**Comment by Shaosil** [comment]
Ok I finally figured out how to fix this - from v1.0.10, reserved item slots will be skipped when shifting items when things are dropped.

**Comment by Bornnemissis** [comment]
Awesome, appreciate the quick work and response can't wait to use it
flawlessly Thank you
