### ISSUE TITLE
[Suggestion]Incomplete display of server list

### ISSUE THREAD

**Issue by smilepeak** [Shaosil/LethalCompanyMods-GeneralImprovements#61]
The server list always shows halfway and stops loading because it's all Chinese servers at night, and I can't find English servers. I believe the author must have restricted something.

And the number of online players in this game makes me certain that the number of servers will not be so small

![123](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/73094803/7b815a7a-40c9-4bf9-ac85-f4db05cd792d)

**Comment by Shaosil** [comment]
Hmm I think I'm going to close this as unplanned - unfortunately I don't plan on touching any server browsing related code. Thanks though.
