### ISSUE TITLE
[Bug]Turning Terminal Screen On+Off causes blue/black bcgrnd desync

### ISSUE THREAD

**Issue by Starstruck1234** [Shaosil/LethalCompanyMods-GeneralImprovements#62]
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/75644243/8215e825-1816-4f69-87ab-6a0bd680d838)

If you have your terminal screens set to have a black background, turning the terminal screen on and off (with the red power button below the "switch camera" button) causes the two original mini-screens to turn on blue, while the rest turn on black.

(Thanks so much for the config options and the mod!)

**Comment by Shaosil** [comment]
Ah interesting catch! I'll fix that if I remember but also there's a huge monitor overhaul update coming soon™! I'll post here when it's live.

**Comment by Shaosil** [comment]
Ok v1.1.0 should be going live shortly, fixing this and more with the monitors. Feel free to use UseBetterMonitors and see the difference!
