### ISSUE TITLE
[Suggestion] Add config option to change external cam resolution and fps too

### ISSUE THREAD

**Issue by NilaierMusic** [Shaosil/LethalCompanyMods-GeneralImprovements#64]
I like the new added monitors with version 1.1.0 and i think they have a lot of potential. But there's also a couple of a problem that i've noticed when reordering monitors around. But a bit of backstory first. Previously i've used [BetterSecurityCameras](https://github.com/stormytuna/BetterSecurityCameras) mod to increase the resolution for the external camera outside of the ship. This works great with it and the monitor screen with increased resolution is still placeable on the new monitors, but it does screw up with the internal camera's custom resolution for some reason, which causes it to revert back to the original resolution. [stormytuna](https://github.com/stormytuna) doesn't seem to care about checking the issue tracker for their mod, so there's probably no way of fixing this minor incompatibility issue without dropping [BetterSecurityCameras](https://github.com/stormytuna/BetterSecurityCameras) entirely and relying on GeneralImprovements for the monitor resolution handling.

**Comment by Shaosil** [comment]
Good idea! It should be really easy to implement, perhaps by next release 👍🏼

**Comment by Shaosil** [comment]
Implemented in v1.1.1, going live shortly.
