### ISSUE TITLE
[Feature Request] Additional Camera Monitor

### ISSUE THREAD

**Issue by NilaierMusic** [Shaosil/LethalCompanyMods-GeneralImprovements#65]
Since 1.1.0 added new monitors to the left side (4 small and 1 big), i instantly knew that i have to add some sort of a bodycam mod, so it can rest on one of the monitors without replacing the existing one. And, to an extent, you can do that with mods such as [Solo's Bodycams](https://thunderstore.io/c/lethal-company/p/CapyCat/Solos_Bodycams/) and [Helmet Cameras](https://thunderstore.io/c/lethal-company/p/RickArg/Helmet_Cameras/). The issue with both of them is, they do actually replace the external ship camera display with their own and replace internal camera display with the external one instead, so, at the end of the day, you do lose the internal camera view, which might not be that crucial, but it does help you to look at the ship's interior and behind youк back when you're on the camera duty, so you would have time to react if a rogue mimic or dog suddenly sneaks up on you while you're busy.

So, it would be great to have, either another, optional monitor that would display internal ship camera, or a monitor that would somehow act as a binder for all other bodycam mods to assign their cameras to it instead of replacing existing monitors.

Also, [OpenBodyCams](https://github.com/Zaggy1024/LC_OpenBodyCams/) doesn't seem to work with GeneralImprovements's `UseBetterMonitors` feature and bodycamera just shows up as a green, empty screen without any errors in the console.
![Lethal_Company_fqS4YzdVNn](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/86863646/c1172752-916b-4e09-9073-eff3f99539d8)
Will probably open an issue on this matter on OpenBodyCams github too and edit a link to it in this issue too.

**Comment by Shaosil** [comment]
Sooo about that. I actually use the HelmetCam mod myself but noticed the slight incompatibility earlier as well.

But guess what's on my backlog? Making my own helmet cam integration... Lol. Hopefully soonish

**Comment by NilaierMusic** [comment]
> Sooo about that. I actually use the HelmetCam mod myself but noticed the slight incompatibility earlier as well.
> 
> But guess what's on my backlog? Making my own helmet cam integration... Lol. Hopefully soonish

Sooo... Should i report this incompatibility to OpenBodyCams mod or not..? I just don't know if i should put this work on someone else too if you're going to implement your own solution to player cameras 'soonish'

**Comment by Shaosil** [comment]
It's your call but to be honest it's a little tricky for them to implement because they rely on an existing material to overwrite. So even if they fix it (if it's theirs to fix), it will still end up overwriting monitor settings from my mod.

I'd just chalk it up to an incompatibility for now

**Comment by NilaierMusic** [comment]
Well, i guess we can just leave this issue open in here as a heads-up for people that want to use OpenBodyCams with GeneralImprovements and then close it once you implements your own head cameras, since that would mean people wouldn't really need to use other modded implementations. (Also, would be cool to have one changing monitor for all cameras or be able to have multiple cameras for each person, since we now have +4 smaller monitors.(but i'm getting ahead of myself in here))

**Comment by NilaierMusic** [comment]
Apparently [Zaggy1024](https://github.com/Zaggy1024) went ahead and added [GeneralImprovements Compatibility](https://github.com/Zaggy1024/LC_OpenBodyCams/commit/b31ff182b9b05b88dec3b2ba8eda50401b28d471) in [OpenBodyCams](https://github.com/Zaggy1024/LC_OpenBodyCams) version 1.0.13+

Still gonna keep this issue, but only as a feature request and Shaosil can close it once body cam feature is officially implemented.

**Comment by Shaosil** [comment]
I think I'm going to close this as unplanned. Originally I wanted to do my own bodycam code, but Zaggy has put a ton of effort into OpenBodyCams and it integrates so well with GI that I don't feel the need to anymore. I also recommend his other mods!

**Comment by NilaierMusic** [comment]
Yeah, that's pretty understandable. Zaggy also deserves all the recognition he can get!
