### ISSUE TITLE
setting for blue monitors/ putting them on all the monitors only works with better monitors enabled.

### ISSUE THREAD

**Issue by DeathWrench** [Shaosil/LethalCompanyMods-GeneralImprovements#66]
How to reproduce: 
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/45341450/17fd0955-b61a-48e8-b630-558f72c34101)
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/45341450/ea029df9-a8bc-41e9-87d6-567aa4602daf)

**Comment by Shaosil** [comment]
This is actually by design (and noted in the description of the config). But I don't remember if I left it out for a specific reason or if it's easily doable. I'll update here once I verify.

**Comment by Shaosil** [comment]
Implemented in v1.1.1, going live shortly.
