### ISSUE TITLE
New Update Broke Corporate Restructure Compat

### ISSUE THREAD

**Issue by EchoLWS999** [Shaosil/LethalCompanyMods-GeneralImprovements#68]
Your mod no longer works with Corporate Restructure at all. Before the update I had show sales set to the 6th monitor to fill the only monitor CR doesn't use. Now no matter what I do there is something wrong. Set them all to zero so CR can be the monitors instead? Nothing shows up as it completely disables the monitors. Everything has to have a value meaning no matter what they'll all end up on one monitor for other workarounds. Please help me workaround this or fix this, very annoying.

**Comment by NilaierMusic** [comment]
Probably an issue on your end. It works fine with Corporate Restructure in my 107 mods modpack.
![Lethal_Company_y2Akam301l](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/86863646/2d72d605-30d1-4515-988c-6a65d2044ce7)

**Comment by EchoLWS999** [comment]
I'll look into remaking my pack then, thanks
