### ISSUE TITLE
Compatibility issue with Advanced Company

### ISSUE THREAD

**Issue by Hardeh** [Shaosil/LethalCompanyMods-GeneralImprovements#7]
Seems like mod can't distinguish equipment slots from normal slots, making weird stuff happen, like nightvision unequip when you drop any loot, or nightvision and loot in the same slot.
Advanced Company can be found here: https://thunderstore.io/c/lethal-company/p/PotatoePet/AdvancedCompany/

**Comment by Shaosil** [comment]
Gotcha, I plan on looking into the drop and rearrange code soon to fix compatibility issues where possible. In the meantime, try toggling the RearrangeOnDrop config option to disable that behavior.

**Comment by Shaosil** [comment]
I have this "fixed" in v1.0.10. It unfortunately means that anything that the PickupInOrder and RearrangeOnDrop settings simply won't function. AdvancedCompany is doing too much with the inventory management and it was much easier to disable my own code in those instances if it was loaded.
