### ISSUE TITLE
Compatibility issue with Fix Personal Scanner option and Better Item Scan mod

### ISSUE THREAD

**Issue by broken-usb** [Shaosil/LethalCompanyMods-GeneralImprovements#70]
Having the "Fix Personal Scanner" option enabled with the "Better Item Scan" mod completely breaks the Scanner and spits out a ton of errors into the console.

**Comment by Shaosil** [comment]
Yeah this is a known issue (see #26) because that mod is touching the same functions as FixPersonalScanner (and more). It's a pure mod clash because they are trying to do very similar things, and there's no way to use both of those at the same time.
