### ISSUE TITLE
[Bug] New update completely broke the monitors

### ISSUE THREAD

**Issue by NilaierMusic** [Shaosil/LethalCompanyMods-GeneralImprovements#77]
Captain, i think we have a bit of an issue here...
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/86863646/8d9b9bbe-202f-4291-96c8-9cea2c3ebf35)
No additional mods installed. Probably caused by these errors that pop up in the console:
```cs
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GeneralImprovements.Utilities.MonitorsHelper.CreateNewStyleMonitors () (at <2f6d08b894ef408e8a4bd9631e41ba58>:0)
GeneralImprovements.Utilities.MonitorsHelper.CreateExtraMonitors () (at <2f6d08b894ef408e8a4bd9631e41ba58>:0)
GeneralImprovements.Patches.StartOfRoundPatch.Start (StartOfRound __instance) (at <2f6d08b894ef408e8a4bd9631e41ba58>:0)
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::Start>(StartOfRound)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GeneralImprovements.Assets.Monitors.Start () (at <2f6d08b894ef408e8a4bd9631e41ba58>:0)
```

**Comment by NilaierMusic** [comment]
Doesn't happen with `UseBetterMonitors` on `false` though.

**Comment by Shaosil** [comment]
Did you by chance install this manually, and if so, did you copy the latest version of the assets file to the same directory as the dll?

**Comment by NilaierMusic** [comment]
> Did you by chance install this manually, and if so, did you copy the latest version of the assets file to the same directory as the dll?

Whoops, my bad. I guess i've overlooked updating the assets file when installing the new version. Issue closed. Don't forget to update assets, kids!
