### ISSUE TITLE
[Suggestion] Add a Crew Status monitor

### ISSUE THREAD

**Issue by NilaierMusic** [Shaosil/LethalCompanyMods-GeneralImprovements#79]
A new monitor that shows nicknames of currently connected people (trimmed or written in the smaller font if it's too long) and indicates when someone died and their body got brought back on the ship (different colored font) or disconnected (removes nickname from the monitor).
Silly concept mock-up:
![37_20240127152949](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/86863646/a69f70fb-8702-4727-ab68-2717730570fd)

If possible, add people's steam avatars and ranks to this monitor along with displaying who's the host of this lobby.
![37_1](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/86863646/d9459710-a0db-4e9b-aa27-2b374db3c10c)
Maybe also show a little animation that would overlay on top of nicknames that would show a value of scrap certain people brought on the ship this day or even during the entire run.
![37_3](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/86863646/176a3b55-6d91-4901-b7a3-c8f867d8b0dd)
Probably should be scrollable as an animation or be able to write down nicknames and pfps in smaller sizes to support mods that extend the lobby size.

**Comment by Shaosil** [comment]
This is a bit of work compared to regular text monitors but I like the idea, I'll keep this issue up for a backlog item

**Comment by Shaosil** [comment]
Added in v1.3.5
