### ISSUE TITLE
[1.0.10] Disorienting fire entry

### ISSUE THREAD

**Issue by throwitaway99** [Shaosil/LethalCompanyMods-GeneralImprovements#8]
This began in 1.0.9 (I marked it as 1.0.10 just to show that I've also tested in 1.0.10), and the issue is that, upon entering a fire exit as a client connected to a host (whether or not the host has the mod), it will for a split second show the fire exit door before flipping the player around. The issue is not present if playing as the host. I find that it is quite disorienting, and was not an issue in 1.0.8. I have provided a video to demonstrate.

https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/136512585/b9697150-ff67-4821-bc35-f7cc2940dbbb

**Comment by Shaosil** [comment]
Ah, I think I know why. I'll try to have this fixed in the next update :)

**Comment by Shaosil** [comment]
Fixed in v1.0.11 which should be live shortly
