### ISSUE TITLE
UnlockOnStart by mrov not taking effect when this mod is loaded

### ISSUE THREAD

**Issue by Re-VelatoR** [Shaosil/LethalCompanyMods-GeneralImprovements#81]
Has something to do with a recent update to one of the two mods. Unsure what's going on. Can't find any logs to help me indicate the problem.

**Comment by NilaierMusic** [comment]
Don't see any issues with two mods. Tried GeneralImprovements 1.1.1 and [UnlockOnStart](https://github.com/AndreyMrovol/LethalUnlockOnStart) 0.6.2 and both of them work together without any issues. Check your config for [UnlockOnStart](https://thunderstore.io/c/lethal-company/p/mrov/UnlockOnStart/) or try disabling other mods.

https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/86863646/e3e4c71e-7f7c-4bbd-9d1a-8fd66b21d9d3

**Comment by Noranecore** [comment]
> Don't see any issues with two mods. Tried GeneralImprovements 1.1.1 and [UnlockOnStart](https://github.com/AndreyMrovol/LethalUnlockOnStart) 0.6.2 and both of them work together without any issues. Check your config for [UnlockOnStart](https://thunderstore.io/c/lethal-company/p/mrov/UnlockOnStart/) or try disabling other mods.
> Itjustworks.mp4

Also ran into this issue with an isolated profile. I've narrowed down the conflict to the SpeakerPlaysIntroVoice config option. If you have this disabled, UnlockOnStart will not function properly.

**Comment by Shaosil** [comment]
Excellent info, thanks! I'll try to see why this is happening.

**Comment by Noranecore** [comment]
> Excellent info, thanks! I'll try to see why this is happening.

From the changelog of IntroTweaks:
```
Some silly mod devs patch PlayFirstDayShipAnimation to implement their code, IT will no longer exit this early.
The speaker SFX is now stopped at the end of the firstDayAnimation enumerator instead.
```
I tried using a version of IntroTweaks before this update and it causes the same exact issue as your mod, so there is your solution.

**Comment by NilaierMusic** [comment]
> > Excellent info, thanks! I'll try to see why this is happening.
> 
> From the changelog of IntroTweaks:
> 
> ```
> Some silly mod devs patch PlayFirstDayShipAnimation to implement their code, IT will no longer exit this early.
> The speaker SFX is now stopped at the end of the firstDayAnimation enumerator instead.
> ```
> 
> I tried using a version of IntroTweaks before this update and it causes the same exact issue as your mod, so there is your solution.

Once again, i've tried [IntroTweaks](https://github.com/Owen3H/IntroTweaks) v1.4.1 (before the `PlayFirstDayShipAnimation` patch) with [UnlockOnStart](https://github.com/AndreyMrovol/LethalUnlockOnStart) v0.6.2 and core functionality worked fine. Even some modded decorations unlocked early (mirror, chess board). The only problem i've noticed is the fact that modded suits didn't unlock, so it resulted in just an empty drawer.
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/86863646/6cca6f2d-0de7-45bc-a8c0-39289d2a601d)
Aside from that, every upgrade spawned fine.

**Comment by Noranecore** [comment]
> > > Excellent info, thanks! I'll try to see why this is happening.
> > 
> > 
> > From the changelog of IntroTweaks:
> > ```
> > Some silly mod devs patch PlayFirstDayShipAnimation to implement their code, IT will no longer exit this early.
> > The speaker SFX is now stopped at the end of the firstDayAnimation enumerator instead.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tried using a version of IntroTweaks before this update and it causes the same exact issue as your mod, so there is your solution.
> 
> Once again, i've tried [IntroTweaks](https://github.com/Owen3H/IntroTweaks) v1.4.1 (before the `PlayFirstDayShipAnimation` patch) with [UnlockOnStart](https://github.com/AndreyMrovol/LethalUnlockOnStart) v0.6.2 and core functionality worked fine. Even some modded decorations unlocked early (mirror, chess board). The only problem i've noticed is the fact that modded suits didn't unlock, so it resulted in just an empty drawer. ![image](https://private-user-images.githubusercontent.com/86863646/300267913-6cca6f2d-0de7-45bc-a8c0-39289d2a601d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NTE5MzUsIm5iZiI6MTcwNjQ1MTYzNSwicGF0aCI6Ii84Njg2MzY0Ni8zMDAyNjc5MTMtNmNjYTZmMmQtMGRlNy00NWJjLWE4YzAtMzkyODlkMmE2MDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDE0MjAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NGVlM2YyMDQ2MjkwOTY3ZWVhNWM4ZTViMmVmN2EzZTc1NjNmN2Y1M2U1ZjNiYWM1MDQ4NzVlM2NlODY2MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RDUYCpx8tEaOwFqh9CLb4C27938sISE-OCFua00e2II) Aside from that, every upgrade spawned fine.

With all due respect, you are just wrong. Please do proper testing before making such strong claims.
https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/19768379/3fdaea78-627b-455c-b069-a29d2e97595f

**Comment by Shaosil** [comment]
Well either way, I have the UnlockOnStart incompatibility fixed and it will be in the next udpate.

**Comment by Shaosil** [comment]
Fixed in v1.1.2, going live shortly

**Comment by AndreyMrovol** [comment]
Hey, I'm the creator of UnlockOnStart - thank you for this fix! 💙

**Comment by Shaosil** [comment]
> Hey, I'm the creator of UnlockOnStart - thank you for this fix! 💙

No worries! The technical details are that I was simply cancelling out of the playIntro function (I forget the name) with a prefix, since most of its purpose was just to play a sound. But since you were hooked into that for something, if it didn't run, your code was never reached. I ended up just nulling out the audio clip instead, I expected that to generate warnings but I didn't see any.

**Comment by AndreyMrovol** [comment]
Well, I'm glad it didn't cause you any **_serious_** issues - thanks again for the quick fix 😅
