### ISSUE TITLE
[Suggestion] Add "Credits" monitor

### ISSUE THREAD

**Issue by ajsglist** [Shaosil/LethalCompanyMods-GeneralImprovements#84]
The only feature I've been missing from CorporateRestructure is having current Credit balance on a monitor.  If possible, I would love to have the ability to add current credits to one of the monitors.

Thanks for the consideration.

**Comment by Shaosil** [comment]
Definitely planned! And soon.

**Comment by Shaosil** [comment]
This is implemented in v1.1.3, going live soon
