### ISSUE TITLE
would you please seperate out the monitors part into a new mod, and there are some issues when using reserveditemslot mods

### ISSUE THREAD

**Issue by Kingtonberry** [Shaosil/LethalCompanyMods-GeneralImprovements#87]
the extra monitors portion(or parts of it) is still affecting the monitors even with it turned off, so mods like corporate restructure are being overwritten with this mod installed it seems. and i love the held item slots cycling to the left for easy dropping in the ship, but it seems to be duplicating the slots taken up at times like reloading or randomly when reserveditemslot mods are going at the same time.

**Comment by Shaosil** [comment]
As of v1.1.3, any monitor tweasks should be completely disabled so long as you don't have monitor config options set to things other than their defaults.

I'm not sure exactly what you mean about the ReservedItems bugs though - I'll try to test that myself eventually.
