### ISSUE TITLE
how to make monitorbackgroundcolor transparent like it was in 1.1.1? bugs as well

### ISSUE THREAD

**Issue by ytitnE** [Shaosil/LethalCompanyMods-GeneralImprovements#88]
First one is 1.1.1, Second one is 1.1.2
[bug] also it seems scrap in ship is not updating until in orbit, and when bettermonitors off, the deadline doesnt go down
![Screenshot (70)](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/157550527/f5af754a-53bc-49bd-a124-68ad58e2ddb3)
![Screenshot (71)](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/157550527/85c66722-47c1-439d-a1a0-e69b7d368dae)

**Comment by Shaosil** [comment]
This was a bug that should be resolved in v1.1.3, going live soon
