### ISSUE TITLE
Please add the ability to completely toggle off any monitor tweaking. 

### ISSUE THREAD

**Issue by ConnaKazie** [Shaosil/LethalCompanyMods-GeneralImprovements#89]
The mod is causing issues from not updating the quota, not displaying the correct deadline, and its because I am forced to tell the game in the config to display these two screens instead of letting the base game do it. I love all the features this mod brings, but jesus christ the monitor portion is incredibly buggy. Please just add a toggle in the config that ENTIRELY shuts off any changes to the monitors. Also the medkit doesn't work, just tells me that my health is full.

**Comment by Shaosil** [comment]
Thanks for the feedback - what I'll do in the next update is detect if there are any monitor tweaks in the config, and if not, do absolutely nothing with monitors. Sorry for the bugs. I'll look into the medkit thing as well.

**Comment by Shaosil** [comment]
As of v1.1.3, no monitor tweaks will be applied if your [ExtraMonitors] config section items are all default. Going live soon.
