### ISSUE TITLE
[1.0.10] Clipboard & Sticky notes floating stuck on the wall

### ISSUE THREAD

**Issue by SrMoroxide** [Shaosil/LethalCompanyMods-GeneralImprovements#9]
Hello!
I really liked the mod and I'm glad that it corrects several of the game's basic bugs.
The only detail I have found is that when starting the game, I find that the clipboard and the sticky note are positioned strangely on the wall.

I will show how it looks without your mod and with the mod.

Without your mod:
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/152836693/9793bad2-717b-40d8-8966-8e8d902b0de1)

With Your mod:
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/152836693/c5674e0d-7c8f-412a-b62d-59019fbb93e5)

**Comment by SrMoroxide** [comment]
If I had a choice, I would opt to a config that allows these objects to be hidden if enabled.

**Comment by Shaosil** [comment]
Ah I broke it in my last update - thanks for the heads up, I'll have them fixed in v1.0.11 and notify you when that's live. I'll add a config option to hide them as well :)

**Comment by Shaosil** [comment]
Fixed in v1.0.11 which should be live shortly - added the requested config option as well that works for both hosts and clients
