### ISSUE TITLE
Significant FPS drop after version 1.1.0

### ISSUE THREAD

**Issue by setset** [Shaosil/LethalCompanyMods-GeneralImprovements#90]
After update to version 1.1.2 from 1.1.0, my framerate drop like 15% when outside the ship, its like the radar or monitor still rendering when outside the ship.
It seems like the same problem that Openbodycams has experienced before but it's already fixed.

**Comment by Shaosil** [comment]
Hmm, I worked with the developer of OpenBodyCams to fix the issue he also had on his, but one thing you might be able to try is to set the FPS of the internal and external cams to 0, thus unrestricting them.

If that doesn't work, see if disabling UseBetterMonitors works, just to see if that's causing it.

**Comment by setset** [comment]
Yes i already use that suggested setting and enable or disable UseBetterMonitors it still happen but more worse when i enable UseBetterMonitors.
When inside the ship while facing camera latest version is better than 1.1.0, but the degradation only occurs when outside the ship

**Comment by smilepeak** [comment]
After my repeated testing, when ShipExternalCamFPS and ShipInternalCamFPS are set to 1, FPS will improve both inside and outside the ship

**Comment by smilepeak** [comment]
If possible, I would like an option to disable internal and external camera rendering, which should significantly improve FPS

**Comment by Shaosil** [comment]
> After my repeated testing, when ShipExternalCamFPS and ShipInternalCamFPS are set to 1, FPS will improve both inside and outside the ship

That's odd, if the fps are set to 0 and resolution multiplier set to 1, no modifications are being made to those two cameras from vanilla.

Technically if you don't assign those cameras to a monitor, they won't be there at all.

**Comment by setset** [comment]
After lastest update my fps back to normal again, thanks for the fix

**Comment by Shaosil** [comment]
Glad to hear it! Thanks for the update.
