### ISSUE TITLE
[Bug] "Credits" and "Sales" monitors display "ProfitQuota"

### ISSUE THREAD

**Issue by ajsglist** [Shaosil/LethalCompanyMods-GeneralImprovements#91]
using 1.1.3, Credits is set to monitor 2, Sales is set to monitor 8, UseBetterMonitors=false
![GI_monitors](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/139426529/b4fd2fda-0ca7-4592-8d9c-80bdcefdca5f)

**Comment by Shaosil** [comment]
Ah got it, fixed locally and will be in the next release, thanks for the heads up.

**Comment by ajsglist** [comment]
thanks for the continued updates... really appreciate all of the work you're putting in to GI
