### ISSUE TITLE
[Incompatibility] Fast Switching cam targets bug with TwoRadarMaps

### ISSUE THREAD

**Issue by ajsglist** [Shaosil/LethalCompanyMods-GeneralImprovements#95]
I have also reported this incompatibility to TwoRadarMaps.  I'm echoing it here since I'm not sure which mod is best-suited to handle the conflict.

I tested GI + TwoRadarMaps with a player and a radar booster. The main cams work as expected (can switch between the player and the radar booster), but the terminal cams ("view monitor") have an unintended behavior:  While "switch" command properly picks up on Radar Booster targets, the "fast switch" functionality (default "left" and "right" arrows) do not see the Radar boosters and will only target normal Players

cams appear to be correctly separated otherwise, and no error is thrown in the log

**Comment by Shaosil** [comment]
This will be fixed in the next update, I'll update this issue again when it's going live.

**Comment by Shaosil** [comment]
Fixed, thanks to @Zaggy1024 in v1.1.5, going live shortly
